### ISSUE TITLE
[Bug]: CI "windows-2019 build and tests" raises an "invalid syntax" error

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#1970] opened 2021-11-10 20:27 UTC
The CI "windows-2019 build and tests" raises an error:

```
Run .github/workflows/test_simple.bat 'C:\OSGeo4W64\opt\grass\grass80.bat'

D:\a\grass\grass>set grass=C:\OSGeo4W64\opt\grass\grass80.bat 

D:\a\grass\grass>call C:\OSGeo4W64\opt\grass\grass80.bat --tmp-location EPSG:4326 --exec g.region res=0.1 -p 
Fatal Python error: initfsencoding: unable to load the file system codec
  File "C:\OSGEO4~1\apps\Python27\lib\encodings\__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax

Current thread 0x00000db0 (most recent call first):
Error: Process completed with exit code 1.
```

_Originally posted by @neteler in https://github.com/OSGeo/grass/issues/1969#issuecomment-965544310_

**Comment by wenzeslaus** [comment] 2021-11-12 14:23
This seems like Python 2 packages are on path instead of Python 3 ones.

**Comment by petrasovaa** [comment] 2021-12-04 04:32
First appeared in #1904. @landam, @hellik any idea?

**Comment by hellik** [comment] 2021-12-04 15:31
> This seems like Python 2 packages are on path instead of Python 3 ones.

It seems so

**Comment by hellik** [comment] 2021-12-04 15:31
> First appeared in #1904. @landam, @hellik any idea?

@ninsbl any idea?

**Comment by hellik** [comment] 2021-12-04 20:53
> First appeared in #1904. @landam, @hellik any idea?

not sure if #1904 is related here.

I guess we have to check the CI OSGeo4W environment why there is also python 2

@ninsbl any idea?

**Comment by hellik** [comment] 2021-12-04 20:58
`Run .github/workflows/test_simple.bat 'C:\OSGeo4W64\opt\grass\grass80.bat'`

it seems in CI it is still OSGeo4W version 1 with default python 2; python 3 is activated there by a batch file defining environment variables. maybe calling this batch file is missing.

in OSGeo4W version 2, python 2 is dropped.

anyone an idea where in our code the windows CI is managed? @HuidaeCho

**Comment by hellik** [comment] 2021-12-04 21:07
> it seems in CI it is still OSGeo4W version 1 with default python 2; python 3 is activated there by a batch file defining 

yes it is still OSGeo4W version 1:

[osgeo4w.yml](https://github.com/OSGeo/grass/blob/main/.github/workflows/osgeo4w.yml#L25)

```
        run: |
          $exe = 'osgeo4w-setup-x86_64-v1.exe'
```

**Comment by hellik** [comment] 2021-12-04 21:11
> yes it is still OSGeo4W version 1:

then calling the batch file defining the python 3 environment is needed to run the simple test.

the better option is to switch to OSGeo4W version 2 in CI, as version isn't maintained anymore.

**Comment by hellik** [comment] 2021-12-04 21:20
> > yes it is still OSGeo4W version 1:
> 
> then calling the batch file defining the python 3 environment is needed to run the simple test.

this file is living in

`C:\OSGeo4W64\bin\py3_env.bat`

content is

```
SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python37
SET PYTHONPATH=%PYTHONHOME%;%PYTHONHOME%\Scripts
PATH %PYTHONPATH%;%PATH%
```

**Comment by hellik** [comment] 2021-12-04 21:29
> > > yes it is still OSGeo4W version 1:
> > 
> > 
> > then calling the batch file defining the python 3 environment is needed to run the simple test.
> 
> this file is living in
> 
> `C:\OSGeo4W64\bin\py3_env.bat`
> 
> content is
> 
> ```
> SET PYTHONHOME=%OSGEO4W_ROOT%\apps\Python37
> SET PYTHONPATH=%PYTHONHOME%;%PYTHONHOME%\Scripts
> PATH %PYTHONPATH%;%PATH%
> ```

and this py3_env.bat is called by

`C:\OSGeo4W64\apps\grass\grass78\etc\env.bat`

and in GRASS8 this call is dropped due to adaption to OSGeo4W version 2, see [env.bat](https://github.com/OSGeo/grass/blob/main/mswindows/env.bat)

ok,that was in #1904  :-)

**Comment by hellik** [comment] 2021-12-04 21:31
so it seems it's time to OSGeo4W version 2 in CI

**Comment by wenzeslaus** [comment] 2021-12-07 15:25
The OSGeo4W check failed in #1904 showing that the PR breaks the check. However, the check is not required, so GitHub allowed the merge. I can make the check required for merging PRs, so this does not happen again. The original idea was that this check has many external dependencies and making it mandatory for all PRs, i.e., unrelated to Windows, would be impractical. After all, GitHub clearly shows when the checks are failing and when they all pass, so making pass a hard requirement is not always necessary. Let me know what you think.

**Comment by ninsbl** [comment] 2021-12-07 20:14
Sorry for being unresponsive for a while. A bit swapped with other stuff. As you identified correctly, CI is still OSGeo4W V1.

Switching to V2 is prepared, but I would have to make some adjustments in the PR:
https://github.com/OSGeo/grass/pull/1873#issuecomment-949398198

I hoped, we could de-duplicate build recipes and have just one, shared with OSGeo4W, so that what we test is exactly what gets shipped to users. But the process is not so straight forward and dependencies on other repos are probably worse than duplicated code...

Will try to update the swich to V2, so we get CI on windows back....

**Comment by wenzeslaus** [comment] 2021-12-07 21:26
Thanks @ninsbl.

> ...what we test is exactly what gets shipped to users.

That would be nice, but...

> ...dependencies on other repos are probably worse than duplicated code...

I agree. We had somewhat similar situation with Homebrew tests on Travis and ended up removing these tests completely, although the issues there were mostly caused by dependency issues rather than some unexpected de-sync of install scripts.

I think the general idea should be that we have scripts useful enough that they can be and are used downstream, but we should not be using downstream scripts in this repo.

**Comment by wenzeslaus** [comment] 2022-01-20 14:17
The Windows CI runs on 8.0 and main branches. Closing as fixed.

**Closed by wenzeslaus** 2022-01-20 14:17 UTC
Labels: bug, CI
