### ISSUE TITLE
Analysis tools generate error

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#2418] opened 2022-06-06 18:25 UTC
**Describe the bug**
An error is generated in the console when analysis tools are launched from the map display window and a raster has not been selected in the map layer display.  The tools that do this are the profile, histogram (not d.histogram), and scatterplot tools. 

The tools work fine AFAICT, except that there is not a default raster to display. It must be manually selected. There just needs to be an error trap that does not display this error. In GRASS 7.8, a dialog pops up asking to select a raster. The same should happen in GRASS 8. 

This is not urgent, but is something to clean up sometime. 

**To Reproduce**
Display a map (e.g, elevation in the demo data set)
Click on the a tool (e.g., histogram) in the map display window. 

Here is the error: 

```Traceback (most recent call last):
  File "/Applications/GRASS-8.2.app/Contents/Resources/lib/p
ython3.9/site-packages/wx/core.py", line 3407, in <lambda>

lambda event: event.callable(*event.args, **event.kw) )
  File "/Applications/GRASS-8.2.app/Contents/Resources/lib/p
ython3.9/site-packages/wx/lib/plot/plotcanvas.py", line 709,
in _do_update

self._adjustScrollbars()
  File "/Applications/GRASS-8.2.app/Contents/Resources/lib/p
ython3.9/site-packages/wx/lib/plot/plotcanvas.py", line
2930, in _adjustScrollbars

r_current = self._getXCurrentRange()
  File "/Applications/GRASS-8.2.app/Contents/Resources/lib/p
ython3.9/site-packages/wx/lib/plot/plotcanvas.py", line
1710, in _getXCurrentRange

return self.last_draw[1]
TypeError
:
'NoneType' object is not subscriptable
```
**Expected behavior**

**Screenshots**

**System description (please complete the following information):**

- Operating System: Mac OS (but probably other systems as well)
- GRASS GIS version: 7.8 and 8

**Comment by tmszi** [comment] 2022-06-08 19:50
Seem there is bug in wxPython 4.1.1 msw (phoenix) wxWidgets 3.1.5 version.

**To Reproduce**
Steps to reproduce the behavior:

1. Launch wxGUI
2. From the Map Display toolbar invoke Analyze tool menu and choose Profile surface map tool (there is no need to choose/ display a raster map)
3. See error

```
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 8.3\Python39\lib\site-
packages\wx\core.py", line 3407, in <lambda>

lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Program Files\GRASS GIS 8.3\Python39\lib\site-
packages\wx\lib\plot\plotcanvas.py", line 709, in _do_update

self._adjustScrollbars()
  File "C:\Program Files\GRASS GIS 8.3\Python39\lib\site-
packages\wx\lib\plot\plotcanvas.py", line 2930, in
_adjustScrollbars

r_current = self._getXCurrentRange()
  File "C:\Program Files\GRASS GIS 8.3\Python39\lib\site-
packages\wx\lib\plot\plotcanvas.py", line 1710, in
_getXCurrentRange

return self.last_draw[1]
TypeError
:
'NoneType' object is not subscriptable
```

**Additional context**
With wxPython 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5 version the bug doesn't occur.

**Comment by neteler** [comment] 2022-06-16 12:18
Is this a "wontfix" since it works in other wxPython versions?

**Closed** 2022-07-19 02:28 UTC
Labels: bug, GUI
