### ISSUE TITLE
[Bug]  GUI crash on Debian testing with 7.8.4

### ISSUE THREAD

**Issue by micha-silver** [OSGeo/grass#1178] opened 2020-12-15 15:38 UTC
**Describe the bug**
The GUI crashes as soon as I move the mouse pointer into Map Display window

**To Reproduce**

1. Start GRASS with GUI
2. move mouse pointer into Map Display
3. crash (text mode still OK)
4. No error reported (I did `g.gisenv set="DEBUG=2"` ... no errors appear)

**System description (please complete the following information):**

- Linux Debian Testing, after recent updates (incl. python 3.9)
- GRASS GIS version 7.8.4

- details about further software components
    - run `g.version -rge` in a GRASS GIS terminal session 
micha@RMS:~$ g.version -rge
version=7.8.4
date=2020
revision=exported
build_date=2020-12-07
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2020-12-07T09:14:35+00:00
libgis_date=2020-12-07T09:14:35+00:00
proj=7.2.0
gdal=3.2.0
geos=3.8.1
sqlite=3.34.0

    - run `python3 -c "import sys, wx; print(sys.version); print(wx.version())"`
micha@RMS:~$ python3 -c "import sys, wx; print(sys.version); print(wx.version())"
3.9.1 (default, Dec  8 2020, 07:51:42) 
[GCC 10.2.0]
4.0.7 gtk3 (phoenix) wxWidgets 3.0.5

**Additional context**
 - Errors at GUI startup:
micha@RMS:~$ g.gui
Launching <wxpython> GUI in the background, please wait...

(wxgui.py:18064): Gtk-WARNING **: 17:35:40.241: Theme parsing error: gtk.css:5597:11: Not using units is deprecated. Assuming 'px'.

(wxgui.py:18064): Gtk-WARNING **: 17:35:40.241: Theme parsing error: gtk.css:5597:14: '0' is not a valid color name

(wxgui.py:18064): Gtk-WARNING **: 17:35:40.242: Theme parsing error: gtk.css:5831:14: '202020' is not a valid color name

(wxgui.py:18064): Gtk-WARNING **: 17:35:40.242: Theme parsing error: gtk.css:5846:20: Junk at end of value for border-width

(wxgui.py:18064): Gtk-WARNING **: 17:35:40.242: Theme parsing error: gtk.css:5871:20: Junk at end of value for border-width

(wxgui.py:18064): Gtk-WARNING **: 17:35:40.242: Theme parsing error: gtk.css:5898:20: Junk at end of value for border-width

**Comment by nilason** [comment] 2020-12-15 15:53
I guess this is a duplicate of #1123  (and #1169).

**Closed** 2020-12-15 16:04 UTC
Labels: bug

**Comment by micha-silver** [comment] 2020-12-15 16:05
Probably a duplicate of [#1178](https://github.com/OSGeo/grass/issues/1178)

**Comment by micha-silver** [comment] 2020-12-15 16:07
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Yes indeed. 
    So I need to wait for a new wxpython on Debian?
    
    
    On 12/15/20 5:53 PM, nilason wrote:
    
    
      
      I guess this is a duplicate of #1123 (and #1169).
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OSGeo/grass/issues/1178#issuecomment-745382449",
"url": "https://github.com/OSGeo/grass/issues/1178#issuecomment-745382449",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Micha Silver
Arava Drainage Authority
cell: +972-523-665918

**Comment by neteler** [comment] 2020-12-15 17:38
>  Yes indeed.
>  So I need to wait for a new wxpython on Debian?

Likely yes.
Importantly, the Debian maintainer of wxpython needs to know that it has been [fixed upstream](https://github.com/wxWidgets/Phoenix/issues/1847) and cherry-pick it. In Fedora that has happened (related [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1901912)) but no idea about Debian.

**Comment by petrasovaa** [comment] 2020-12-15 19:26
> > Yes indeed.
> > So I need to wait for a new wxpython on Debian?
> 
> Likely yes.
> Importantly, the Debian maintainer of wxpython needs to know that it has been [fixed upstream](https://github.com/wxWidgets/Phoenix/issues/1847) and cherry-pick it. In Fedora that has happened (related [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1901912)) but no idea about Debian.

Or use python < 3.9

**Comment by mlennert** [comment] 2020-12-16 15:47
>  Yes indeed. So I need to wait for a new wxpython on Debian? 

The wxpython bug was reported
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977047,
already solved and available in Debian testing since today:
https://tracker.debian.org/news/1202174/wxpython40-407dfsg-7-migrated-to-testing/

In the grass package the issue was already fixed by Bas earlier with version 7.8.4-3 available in testing since Dec 7.

**Comment by micha-silver** [comment] 2020-12-17 20:13
> In the grass package the issue was already fixed by Bas earlier with version 7.8.4-3 available in testing since Dec 7.

Thanks, got the update and, as you said, the problem is fixed.
