### ISSUE TITLE
[Bug] feature selection in GUI

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#2983] opened 2023-05-25 18:07 UTC
**Describe the bug**
I am trying to select and extract a set of points from a points map, using the selection in the GUI. I query the data and the points I want show up correctly. But if I try to extract them to a new set of points, it generates a weird error (below) and extracts *all* of the points rather than the ones selected. I have tried just selecting them manually and get the same error. But v.select and v.db.select both select and extract the correct points/data. 

Here is the error in the console. Note that I've checked repeatedly and there is no value 'EF5/2' in an integer column. I attach the csv and csvt that I used to import the data and create a points map. 

```
Traceback (most recent call last):
  File "/Applications/GRASS-
8.2.app/Contents/Resources/gui/wxpython/dbmgr/base.py", line
1972, in OnDataDrawSelected

self._drawSelected(zoom=False)
  File "/Applications/GRASS-
8.2.app/Contents/Resources/gui/wxpython/dbmgr/base.py", line
1819, in _drawSelected

cats = list(map(int, fn()))











^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
ValueError
:
invalid literal for int() with base 10: 'EF5/2'
```
**System description (please complete the following information):**

- Operating System: Mac OS 13.3.1 with Apple ARM
- GRASS GIS version 8.2.2

**Attached files**
I've added a 'txt' extension to the csvt because GitHub won't let me upload the original. 

[Status_and_architecture.csv](https://github.com/OSGeo/grass/files/11567972/Status_and_architecture.csv)
[Status_and_architecture.csvt.txt](https://github.com/OSGeo/grass/files/11567988/Status_and_architecture.csvt.txt)

**Comment by tmszi** [comment] 2023-05-26 11:23
Could you share exact command how you import your CSV file as point map and what kind of GUI tool(s) you used for query this point map please?

I imported your CSV file with following module:

```
GRASS test/PERMANENT:~ > v.in.ascii input=/tmp/csv/Status_and_architecture.csv output=status format=point separator=,  skip=1 columns='key_ef TEXT, key_seq INTEGER, key_full TEXT, name_mod1 TEXT, name_mod2 TEXT, name_mod3 TEXT, name_lat1 TEXT, name_lat2 TEXT, name_lat3 TEXT, loc_qual TEXT, is_civ INTEGER, is_mun INTEGER, is_col INTEGER, rank INTEGER, is_mil INTEGER, has_mstone INTEGER, has_bstone INTEGER, has_road INTEGER, has_wall INTEGER, has_fortre INTEGER, has_theatr INTEGER, has_amphth INTEGER, has_acropo INTEGER, has_circus INTEGER, has_odeum INTEGER, has_forum INTEGER, has_macell INTEGER, has_capito INTEGER, has_temple INTEGER, has_triarc INTEGER, has_thbath INTEGER, has_statue INTEGER, has_cister INTEGER, has_aquedu INTEGER, has_bridge INTEGER, has_founta INTEGER, has_mosaic INTEGER, has_column INTEGER, has_oilpre INTEGER, has_church INTEGER, has_basili INTEGER, has_baptis INTEGER, has_nympha INTEGER, has_granar INTEGER, has_quarry INTEGER, has_mine INTEGER, sum_has INTEGER, x REAL, y REAL, x_utm REAL, y_utm REAL' x=47 y=48
```

As GUI query tool I used **Attribute Table Manager** with extracting queried rows into new point vector map and GUI **Select vector feature(s)** tool (with fixed bug #2984) too, but I can't reproduce your error message.

**Comment by cmbarton** [comment] 2023-05-28 07:40
I used db.in.ogr because v.in.ascii does not import field headers. 

Further checking suggests that it has something to do with the way the data are imported and how that interacts with the table manager. If I import a shape file generated from the same data in ArcGIS, the table manager does extract the points correctly. 

However, as In noted, it is not entirely the way the file is imported because v.extract and v.db.extract **do** extract the points correctly.

**Comment by petrasovaa** [comment] 2024-09-25 15:29
I managed to import it with:
```
db.in.ogr  input=Status_and_architecture.csv output=testcsv
v.in.db -t table=testcsv x=x_utm y=y_utm key=cat output=testcsv
```
I tried viewing the attribute table in GUI and extracting the points (in various ways) and everything works fine. So I will close this as not reproducible, but feel free to reopen if you still have issues.

**Closed by petrasovaa** 2024-09-25 15:29 UTC
Labels: bug

**Comment by cmbarton** [comment] 2024-09-25 16:46
I'll test more and hope that all is fixed now.
