### ISSUE TITLE
[Bug] vector data import fails with error in GPJ_transform()

### ISSUE THREAD

**Issue by landam** [OSGeo/grass#542] opened 2020-04-22 13:40 UTC
**Describe the bug**

`v.import` command fails with `GPJ_transform()` error when importing data produced in older GRASS versions in EPSG 5514 CRS.

**To Reproduce**

1. Start GRASS

```
grass79 -c EPSG:5514 C:\grassdata\test_staty --text
```

2. Run import command

```
v.import in=C:\users\martin\Documents\fgis-data\data\shp\ruian\staty.shp out=staty
```

which fails with

```
UPOZORNĚNÍ: proj_trans() failed: latitude or longitude exceeded limits
CHYBA: Error in GPJ_transform() (projection of input coordinate pair)
CHYBA: Unable to to reproject vector <staty>
```

**Expected behavior**

Sample input data was produced by older GRASS version in location defined by EPSG code 5514. Should be imported without any problems.

**System description (please complete the following information):**

- Operating System: Windows 10
- GRASS GIS version 7.9

```
version=7.9.dev
date=2020
revision=f59a1c088
build_date=2020-04-21
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=4e5d2f0c9
libgis_date="Mon Apr 20 13:29:17 2020 +0200"
proj=6.3.1
gdal=3.0.4
geos=3.8.1
sqlite=3.29.0
```

**Comment by metzm** [comment] 2020-04-24 20:37
Can you provide the staty shapefile, or a bbox of this shapfile in the same CRS as the staty shapefile, for testing?

**Comment by neteler** [comment] 2020-08-11 17:58
gentle ping @landam to attach sample data

**Comment by neteler** [comment] 2021-06-03 09:57
Closing since it cannot be reproduced without sample data. Feel free to reopen as needed.

**Closed by neteler** 2021-06-03 09:57 UTC
Labels: bug
