### ISSUE TITLE
Starting GRASS GIS...

### ISSUE THREAD

**Issue by kadlagomkar** [OSGeo/grass#1282] opened 2021-01-29 06:06 UTC
After installing GRASS GIS and launching it I am getting this error:
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\gis_set.py", line 43, in <module>
    from core.gcmd import GMessage, GError, DecodeString, RunCommand
  File "C:\Program Files\GRASS GIS 7.8\gui\wxpython\core\gcmd.py", line 43, in <module>
    from win32file import ReadFile, WriteFile
ImportError: DLL load failed: The specified procedure could not be found.
ERROR: Error in GUI startup. See messages above (if any) and if necessary, please report this error to the GRASS developers.
On systems with package manager, make sure you have the right GUI package, probably named grass-gui, installed.
To run GRASS GIS in text mode use the --text flag.
Use '--help' for further options
     grass78 --help
See also: https://grass.osgeo.org/grass78/manuals/helptext.html
Exiting...
Press any key to continue . . .

**Comment by hellik** [comment] 2021-01-29 06:13
See #1218 for a discussion about this issue with a hint about a local fix. An updated repackaged standalone installer is on the way. 

ping  @landam

**Comment by neteler** [comment] 2021-01-29 16:42
(I'll close this as duplicate of #1218)

**Closed by neteler** 2021-01-29 16:42 UTC
Labels: duplicate
