### ISSUE TITLE
[Feat] XFCE: Better menue tray description of running GRASS GIS session

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2060] opened 2022-01-02 12:23 UTC
**Is your feature request related to a problem? Please describe.**

At time, G8 (and also G7) present themselves like this in the [XFCE Desktop Environment](https://www.xfce.org/)

![image](https://user-images.githubusercontent.com/1295172/147875475-f407e39c-a991-4976-8a19-103bc3bf315e.png)

--> "wxgui.py" which isn't that intuitive...

Clicking on it shows:

![image](https://user-images.githubusercontent.com/1295172/147875505-b9688cd7-d736-4d1e-a4f6-48fefc916ab6.png)

**Describe the solution you'd like**

I'd like to see here

**"[icon] GRASS GIS 8.0.0"**

rather than

"[icon] wxgui.py"

**Comment by petrasovaa** [comment] 2022-01-03 02:37
If you can test, you could add the following line:

```
--- a/gui/wxpython/wxgui.py
+++ b/gui/wxpython/wxgui.py
@@ -66,6 +66,7 @@ class GMApp(wx.App):
         """
         # Internal and display name of the app (if supported by/on platform)
         self.SetAppName("GRASS GIS")
+        self.SetAppDisplayName("GRASS GIS")
         self.SetVendorName("The GRASS Development Team")
 
         # create splash screen
```

**Comment by neteler** [comment] 2022-01-03 09:04
(I can test easily)

Unfortunately the addition of [SetAppDisplayName()](https://docs.wxpython.org/wx.AppConsole.html#wx.AppConsole.SetAppDisplayName) as suggested above does not change anything, at least with XFCE.

So I tried with a wxpython demo (`/usr/lib64/python3.10/site-packages/wx/py/PyCrust.py`) and changed `self.SetAppName()` and `self.SetAppDisplayName()` therein which didn't change anything.

However, when changing in `title` in `/usr/lib64/python3.10/site-packages/wx/py/crust.py` it works (" BLA" added here):

```
class CrustFrame(frame.Frame, frame.ShellFrameMixin):
    """Frame containing all the PyCrust components."""

    name = 'CrustFrame'


    def __init__(self, parent=None, id=-1, title='Py BLA',
                 pos=wx.DefaultPosition, size=wx.DefaultSize,
                 style=wx.DEFAULT_FRAME_STYLE,
                 rootObject=None, rootLabel=None, rootIsNamespace=True,
                 locals=None, InterpClass=None,
                 config=None, dataDir=None,
                 *args, **kwds):
```

![image](https://user-images.githubusercontent.com/1295172/147913937-0142feb9-645e-4d43-8884-9c53b5c42d92.png)


So I wonder if the `self.SetAppDisplayName("GRASS GIS")` needs to be moved elsewhere in the code, maybe to somewhere in `wxpython/lmgr/frame.py`?

**Comment by petrasovaa** [comment] 2022-01-03 14:36
No idea, I think the problem is between XFCE and wx. It works on Ubuntu for example.

**Comment by neteler** [comment] 2022-01-03 14:48
I see, but with or without the change?

**Comment by petrasovaa** [comment] 2022-01-03 15:02
> I see, but with or without the change?

It works currently without the change. I think adding the line there doesn't harm, but probably doesn't do much since we already call SetAppName, see also https://docs.wxwidgets.org/3.0/classwx_app_console.html#a83aa5fdf1e636dc441b62ceb95c8bf5a

**Comment by neteler** [comment] 2022-01-03 17:21
> No idea, I think the problem is between XFCE and wx. It works on Ubuntu for example.

Do you mean the Ubuntu Windows manager (don't recall its standard name).

I tested it on Ubuntu/XFCE, same problem:

![image](https://user-images.githubusercontent.com/1295172/147959878-6803d125-f9dd-4824-9384-cd6047d1a8f8.png)

However, the G7 startup screen looks fine in XFCE:

![image](https://user-images.githubusercontent.com/1295172/147960019-39cd8a62-6f51-4f6e-8dc4-637e3af15f07.png)

So it later looses the title. Not a very important problem, I just try to find out where it gets lost (low prio).

**Comment by wenzeslaus** [comment] 2022-01-03 21:00
I think "works on Ubuntu" means whatever setup comes with standard Ubuntu which is surely not XFCE :-)

According to these screenshots, XFCE takes a window title and uses that in the tray/top bar. When an application has multiple (top level) windows, it ignores the titles (because there is more than one) and uses the executable name.

Unlike other systems, it seems to me XFCE does not use the app name set by the executable assuming you made the change or tried 8.0. (Sorry, I'm not sure what code you are changing and what functions since this is both about 8.0 and 7.8.) 7.8 does not have any of these lines. 8.0 does. I added the _SetAppName_ lines because Gnome Shell, Unity, and macOS were showing things like wxgui.py and Python including a Python icon.

It seems to me that the fix is needed in XFCE, but a single window interface in GRASS will probably address this too (available in the main branch now). Also running GUI directly from `grass.py` instead of a subprocess would likely address this (resulting in grass.py as a name), but that would mean also a lot of other changes and it may not be a good idea.

**Comment by petrasovaa** [comment] 2022-01-05 20:13
Closing this, since there is likely not much we can do.

**Closed by petrasovaa** 2022-01-05 20:13 UTC
Labels: enhancement, GUI
