### ISSUE TITLE
[Bug] Mask not respected in r.out.gdal

### ISSUE THREAD

**Issue by jamesp670** [OSGeo/grass#499] opened 2020-04-10 01:46 UTC
**Describe the bug**

r.out.gdal would logically not output cells outside of the current mask.  It does not do that, in my experiment and also as reported in the unresolved stackoverflow post:

- https://gis.stackexchange.com/questions/226302/how-to-clip-raster-in-grass-gis

**To Reproduce**

The onroad_2010_3count is a raster covering the CONUS.
co_3count is a much smaller in geographical extent vector of areas covering 3 US counties.

1. g.region -a raster=onroad_2010_3count
2. time r.mask raster=onroad_2010_3count vector=co_3count
3. time r.out.gdal input=onroad_2010_3count@dartenative
   output=onroad_2010_3count_aftermask.tif format=GTiff
   createopt="COMPRESS=DEFLATE" --overwrite

Unfortunately its shape is wrong.  

**Expected behavior**
I expect on pixels only inside the counties.
But, I still see pixels outside.

**Screenshots**
![image](https://user-images.githubusercontent.com/34634023/78954864-46cee700-7a92-11ea-9752-444c14f7d626.png)

**System description (please complete the following information):**

- Operating System: Linux  Debian 10
- GRASS GIS version 7.6.0

**Additional context**

If we can resolve this perhaps someone better at stackoverflow than I am can answer the OP mentioned at the top of this report.

**Comment by HuidaeCho** [comment] 2020-04-23 02:20
I cannot reproduce it in the NC sample dataset.
```bash
v.extract input=big_lakes cat=10789 output=a_big_lake
r.mask vect=a_big_lake
r.out.gdal input=elevation output=a_big_lake_elev.tif
```
![test](https://user-images.githubusercontent.com/7456117/80051723-e6ef2c00-84e6-11ea-8a98-53b974ae290e.png)

In your case,
```bash
r.mask raster=onroad_2010_3count vector=co_3count
```
this is incorrect. You said onroad_2010_3count is much bigger than co_3count in extent. If you want to extract the smaller region, you should only specify `vector=co_3count` without the bigger one. If you specify both, it'll use the raster only, which is the entire CONUS.

**Comment by lucadelu** [comment] 2020-11-19 23:11
Closing, reopen if needed

**Closed by lucadelu** 2020-11-19 23:11 UTC
Labels: invalid

**Comment by wenzeslaus** [comment] 2020-11-20 04:18
> If you specify both, it'll use the raster only, which is the entire CONUS.

Isn't the confusion caused by simply ignoring the other option (if that's indeed the case)? Perhaps the issue is bad interface or documentation.
