### ISSUE TITLE
[Bug] g.gui suddenly won't come up, "ERROR: wxGUI requires wxPython."

### ISSUE THREAD

**Issue by jamesp670** [OSGeo/grass#498] opened 2020-04-10 01:16 UTC
**Describe the bug**

Using a vanilla Debian 10/Grass 7.6.0 install, what I expect:

- Grass + addons are not broken by python upgrades

What happens instead:

After a recent python upgrade (automatically installed on my system), I now have to choose:

1. With no environment variables set, the GUI won't launch, saying instead
"ERROR: wxGUI requires wxPython."

or
2. I can set GRASS_PYTHON=python2.7 and now the GUI will launch.  However, the
r.clip add-on won't run, complaining instead:

: GRASS 7.6.0 (rlistask70):~ > time r.clip input=onroad_2010_3count output=onroad_2010_3count_after_r_dot_clip                           
: Traceback (most recent call last):                                                                                                     
:   File "/home/powellj/.grass7/addons/scripts/r.clip", line 45, in <module>                                                             
:     sys.exit(main())                                                                                                                   
:   File "/home/powellj/.grass7/addons/scripts/r.clip", line 33, in main                                                                 
:     original = options['input']                                                                                                        
: KeyError: 'input'                                                                                                                      

**To Reproduce**
On Debian 10,

1. Launch grass 7.6.0.
2. Launch the wx GUI.
3. Run r.clip
Observe a traceback in step 2 and/or in step 3.

**Expected behavior**
I expect all three steps to run flawlessly.

**System description (please complete the following information):**

- Operating System: Linux: Debian 10
- GRASS GIS version 7.6.0

**Comment by neteler** [comment] 2020-04-10 23:01
Can you move to https://github.com/OSGeo/grass/releases/tag/7.8.2? The 7.6.0 is getting really old...

I just tested the example provided in https://grass.osgeo.org/grass7/manuals/addons/r.clip.html and that runs smoothly in 7.8.2.

**Comment by lucadelu** [comment] 2020-11-20 14:32
@jamesp670 could you test newer GRASS version and report if the problem is still valid?

**Comment by neteler** [comment] 2021-12-09 09:42
Closing as "solved in later versions"

**Closed by neteler** 2021-12-09 09:42 UTC
Labels: bug, GUI, Python
