### ISSUE TITLE
wxGUI: Dragging AuiNotebook page raises error [Bug] 

### ISSUE THREAD

**Issue by lindakladivova** [OSGeo/grass#2671] opened 2022-11-30 07:59 UTC
**Describe the bug**
This problem occurs in Single-Window GUI. The error is raised when a user drag Map Notebook page (for example a user works with several map displays (several tabs) and wants to move the first map display tab to the position of the second tab (change positioning).

**To Reproduce**

1. Create more map displays
2. Click on the first map notebook tab and try to drag it somewhere else
3. The positioning of map display tabs is correctly changed
4. However, in the Console, you see this error:
  C++ assertion ""win && m_cr"" failed at /home/wxpy/wxPython-
  4.2.0/ext/wxWidgets/src/gtk/overlay.cpp(98) in Init():
  invalid dc for wxOverlay
  Traceback (most recent call last):
    File "/home/linduska/.local/lib/python3.10/site-
  packages/wx/lib/agw/aui/auibook.py", line 2451, in OnMotion
  
  self._drag_image.Move(pos)
  wx._core
  .
  wxAssertionError
  :
  C++ assertion ""win && m_cr"" failed at /home/wxpy/wxPython-
  4.2.0/ext/wxWidgets/src/gtk/overlay.cpp(98) in Init():
  invalid dc for wxOverlay

**Expected behavior**
An error should not be raised.

**Screenshots**
![Screenshot from 2022-11-30 08-48-34](https://user-images.githubusercontent.com/49241681/204737582-95483b95-3497-4cb1-ba9c-5e03ad819925.png)

**System description (please complete the following information):**

- Operating System: [Ubuntu 22.04.1 LTS]
- GRASS GIS version [8.3 (main)]
- wxPython: 4.2.0

**Comment by petrasovaa** [comment] 2022-12-01 03:41
Weird, I can't reproduce this one either.

**Comment by tmszi** [comment] 2022-12-03 08:48
I can't reproduce this with:

1. OS GNU/Linux (Gentoo distribution)

- Python: 3.11.0, wxPython: 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0
- Python: 3.10.8, wxPython: 4.2.0 gtk3 (phoenix) wxWidgets 3.2.0
- Python: 3.9.15, wxPython: 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5
- Python: 3.8.15, wxPython: 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5

2. OS MS Windows

- Python: 3.9.5, wxPython: 4.2.0 msw (phoenix) wxWidgets 3.2.1

**Comment by lindakladivova** [comment] 2022-12-03 11:17
It is weird, maybe it is a matter of the new Ubuntu itself? But it is really weird because this error seems directly related to wx.

Besides those two bugs https://github.com/OSGeo/grass/issues/2671 and https://github.com/OSGeo/grass/issues/2672, I for example also experienced problematic rendering of upper pane parts after resizing.
![Screenshot from 2022-12-03 12-08-14](https://user-images.githubusercontent.com/49241681/205437983-cbec5328-d31b-4f6f-9c26-8023c3ab60bc.png)
But after some time it fixes automatically and I have not observed any special patterns when happens so. Just sometimes it happens and fixes, sometimes does not..
Do you have a similar experience?

**Comment by tmszi** [comment] 2022-12-03 15:25
> It is weird, maybe it is a matter of the new Ubuntu itself? But it is really weird because this error seems directly related to wx.

Under Gentoo distribution is official wxPython ebuild (package) version 4.0.7 https://packages.gentoo.org/packages/dev-python/wxpython. 

I installed wxPython 4.2.0 version inside virtualenv by pip command:

1. `test@test:~$ DIR=$HOME/wxPy420 && mkdir $DIR && cd $DIR`
3. `test@test:~/wxPy420$ virtualenv --python 3.10 venv`
4. `test@test:~/wxPy420$ source venv/bin/activate`
5.  Install wxPython attrdict py package dependency (which support Python 3.10 version) `(venv)test@test~/wxPy420$ pip install git+https://github.com/TelePay-cash/attrdict.git`
6. Install wxPython version 4.2.0 [last release ](https://pypi.org/project/wxPython/4.2.0/#history)`test@test:~/wxPy420$ pip install wxPython`
7. Compilation take some time

When I look at the Ubuntu distribution 22.04 LTS (Jammy Jellyfish) and 22.10 (Kinetic Kudu) they use [wxPython 4.0.7 version](https://packages.ubuntu.com/search?keywords=wxPython&searchon=names&suite=all&section=all).

How do you install wxPython version 4.2.0?

> Besides those two bugs #2671 and #2672, I for example also experienced problematic rendering of upper pane parts after resizing. ![Screenshot from 2022-12-03 12-08-14](https://user-images.githubusercontent.com/49241681/205437983-cbec5328-d31b-4f6f-9c26-8023c3ab60bc.png) But after some time it fixes automatically and I have not observed any special patterns when happens so. Just sometimes it happens and fixes, sometimes does not.. Do you have a similar experience?

I have tried resizing this pane, the main window, in various ways, but I cannot reproduce it.

**Comment by lindakladivova** [comment] 2022-12-04 08:04
I 

> > It is weird, maybe it is a matter of the new Ubuntu itself? But it is really weird because this error seems directly related to wx.
> 
> Under Gentoo distribution is official wxPython ebuild (package) version 4.0.7 https://packages.gentoo.org/packages/dev-python/wxpython.
> 
> I installed wxPython 4.2.0 version inside virtualenv by pip command:
> 
>     1. `test@test:~$ DIR=$HOME/wxPy420 && mkdir $DIR && cd $DIR`
> 
>     2. `test@test:~/wxPy420$ virtualenv --python 3.10 venv`
> 
>     3. `test@test:~/wxPy420$ source venv/bin/activate`
> 
>     4. Install wxPython attrdict py package dependency (which support Python 3.10 version) `(venv)test@test~/wxPy420$ pip install git+https://github.com/TelePay-cash/attrdict.git`
> 
>     5. Install wxPython version 4.2.0 [last release ](https://pypi.org/project/wxPython/4.2.0/#history)`test@test:~/wxPy420$ pip install wxPython`
> 
>     6. Compilation take some time
> 
> 
> When I look at the Ubuntu distribution 22.04 LTS (Jammy Jellyfish) and 22.10 (Kinetic Kudu) they use [wxPython 4.0.7 version](https://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=python3-wxgtk4.0&searchon=names).
> 
> How do you install wxPython version 4.2.0?
> 
@tmszi thank you for your analysis. :-) I have installed it as follows:
pip install -U \
    -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04 \
    wxPython
Then wxPython did not work due to the error _libsdl2-2.0so.0 cannot open shared object file_
which I fixed by 
sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

Then everything seemed alright. So indeed those bugs are probably related to the unhealthy new wxPython version on Ubuntu.

> > Besides those two bugs #2671 and #2672, I for example also experienced problematic rendering of upper pane parts after resizing. ![Screenshot from 2022-12-03 12-08-14](https://user-images.githubusercontent.com/49241681/205437983-cbec5328-d31b-4f6f-9c26-8023c3ab60bc.png) But after some time it fixes automatically and I have not observed any special patterns when happens so. Just sometimes it happens and fixes, sometimes does not.. Do you have a similar experience?
> 
> I have tried resizing this pane, the main window, in various ways, but I cannot reproduce it.

**Comment by petrasovaa** [comment] 2022-12-06 04:36
So can we close this?

**Closed** 2022-12-06 06:44 UTC
Labels: bug, GUI
