### ISSUE TITLE
[Bug] CI on main failing due to dependencies

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#3662] opened 2024-04-24 13:55 UTC
## Describe the bug

CI on main failing due to not signed dependencies (not our issue directly). Some PR runs seem to be working.

## To reproduce

Check main.
## Screenshots

```
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [848 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [163 kB]
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
Error: Process completed with exit code 100.
```

## System description

- Operating System: Ubuntu in CI
- GRASS GIS version: main, PRs?

**Comment by echoix** [comment] 2024-04-24 13:56
See https://github.com/OSGeo/grass/pull/3627#issuecomment-2074986334

**Comment by echoix** [comment] 2024-04-24 13:57
I didn't have time earlier this morning to write about not merging until the issue is resolved.

**Comment by neteler** [comment] 2024-04-24 14:10
This is a GitHub glitch (now apparently fixed), see:

https://github.com/microsoft/linux-package-repositories/issues/130

I take liberty to close this.

**Closed by neteler** 2024-04-24 14:10 UTC
Labels: bug, CI

**Comment by echoix** [comment] 2024-04-24 14:24
But the GitHub status 14 mins ago mentioned that they continue to see "consistent impact" so their fixes on all the issues didn't work, probably the Ubuntu one yes.
