### ISSUE TITLE
g.extension issue after an upgrade

### ISSUE THREAD

**Issue by xyleme** [OSGeo/grass#2924] opened 2023-04-19 11:59 UTC
Upgrading to grass_master, as usual I was warned to update my addons with g.extension.
It failed, returning the following message:

```
g.extension.all -f
[...]
------------------------------------------------------------
Reinstalling extension <v.out.ply>...
------------------------------------------------------------
ERROR: Download file from
       <https://api.github.com/repos/OSGeo/grass-addons/git/trees/grass7?recursive=1>,
       failed. Check internet connection.
ERROR: Unable to process extension:v.out.ply
------------------------------------------------------------
```

I am operating on Debian Bullseye machine:

5.10.162-1 (2023-01-21) x86_64 GNU/Linux

```
g.version -rge
version=8.3.dev
date=2023
revision=24ce8d3191
build_date=2023-04-19
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=a82501dc85
libgis_date=2023-02-27T12:45:25+00:00
proj=7.2.1
gdal=3.2.2
geos=3.9.0
sqlite=3.34.1
```

**Comment by tmszi** [comment] 2023-04-19 14:36
Seem there is issue with verification SSL certificate during download data from the GitHub REST API server.

Quick fix:

```
tomas@gentoo-gnu-linux:~$ cd /tmp && git clone --no-checkout --filter=tree:0 https://github.com/osgeo/grass-addon && cd /tmp/grass-addons

tomas@gentoo-gnu-linux:/tmp/grass-addons$ git sparse-checkout init && git sparse-checkout set src/vector/v.out.ply && git checkout grass8

# Inside GRASS GIS terminal session
GRASS nc_basic_spm_grass7/PERMANENT:~ > g.extension v.out.ply url=/tmp/grass-addons/src/vector/v.out.ply/
```

**Comment by xyleme** [comment] 2023-04-19 17:36
Thank you Tomas!

**Comment by cmbarton** [comment] 2023-04-20 21:30
I just recompiled GRASS 8.3 today (20 April 2023) on my Mac (ARM M2 Ventura). 

g.extension was working with a prior build of 8.3 from January 2023, with SVN installed. Now it fails with the following error:

```8.3.app/Contents/Resources/scripts/g.extension", line 260,
in _get_version
    return float(
           ^^^^^^
ValueError: could not convert string to float: 'Git-143)'
```

**Comment by tmszi** [comment] 2023-04-21 03:51
> I just recompiled GRASS 8.3 today (20 April 2023) on my Mac (ARM M2 Ventura).
> 
> g.extension was working with a prior build of 8.3 from 3 April 2023, with SVN installed. Now it fails with the following error:
> 
> ```
> in _get_version
>     return float(
>            ^^^^^^
> ValueError: could not convert string to float: 'Git-143)'
> ```

Git package is new dependency required for launching g.extension module. We can add it as new required dependency for GRASS GIS compilation/build process. Is it package installed on your OS?

**Comment by petrasovaa** [comment] 2023-04-21 12:52
> Git package is new dependency required for launching g.extension module. We can add it as new required dependency for GRASS GIS compilation/build/installation process. Is it package installed on your OS?

It looks like it is installed, but could you run `git --version` in the command line? For example, I get `git version 2.25.1`. But looking at [this](https://stackoverflow.com/questions/59937305/do-i-have-2-kinds-of-git-installed-in-my-mac-if-so-which-one-will-be-used-by-d) you may have something like `git version 2.21.1 (Apple Git-122.3)` so the parsing is currently not robust enough. Given the [git --version code](https://github.com/git/git/blob/master/help.c), we could perhaps assume the third item is always the version?

**Comment by cmbarton** [comment] 2023-04-21 15:44
I have an ARM Mac M2 with Ventura. Here is my Git version

```
git version
git version 2.39.2 (Apple Git-143)
```

**Comment by nilason** [comment] 2023-04-21 16:30
Git is not included as dependency in Mac app build script. Good this was discovered! Will add it as soon as possible.

**Comment by cmbarton** [comment] 2023-04-21 19:43
Thanks Nicklas

**Comment by nilason** [comment] 2023-04-21 20:51
> Git is not included as dependency in Mac app build script. Good this was discovered! Will add it as soon as possible.

@cmbarton Just added git (v2.40), please refresh the scripts and try again.

**Comment by nilason** [comment] 2023-04-21 21:02
Reading back this thread I realise the Mac issue is not lack of or too old git, but the parsing of the version. The Apple-git version you have will work fine when the version parsing is fixed. Packaging git with the app bundle is nevertheless a precaution for older macOS versions.

**Comment by cmbarton** [comment] 2023-04-21 21:16
Ah. Once g.extension is updated I'll compile again.

**Comment by tmszi** [comment] 2023-04-22 03:48
Fixed with #2929.

**Comment by cmbarton** [comment] 2023-04-24 21:14
I recompiled and tested on the Mac, both ARM and Intel versions. 

g.extension works fine now. I posted updated versions of 8.3. 

Thanks all.

**Comment by nilason** [comment] 2023-04-24 21:26
The Mac issue Is different from the original issue reported here.
It is the added git dependency package in build script  that fixed the Mac build. Glad it works!

**Comment by cmbarton** [comment] 2023-04-24 21:39
I thought it was the update to g.extension. Sorry

**Comment by tmszi** [comment] 2023-04-27 11:34
Could @xyleme try these tests, please? I could not reproduce your error.

1. Test

Save Python code as test1.py script file and run it with `python test1.py`

```python
from urllib import request as urlrequest

try:
    request = urlrequest.Request(
        "https://github.com/OSGeo/grass-addons/tree/grass8/src/vector/v.out.ply",
        headers={"User-Agent": "Mozilla/5.0"},
    )
    response = urlrequest.urlopen(request)
    print(response.code)
except urlrequest.HTTPError as e:
    print(e.code)
except urlrequest.URLError as e:
    print(e.args)
```

2. Test

Save Python code as test2.py script file and run it with `python test2.py`

Require Python package `ceritfi` to be installed (`sudo apt-get install python3-certifi`).

```python
import ssl
from urllib import request as urlrequest

import certifi

try:
    request = urlrequest.Request(
        "https://github.com/OSGeo/grass-addons/tree/grass8/src/vector/v.out.ply",
        headers={"User-Agent": "Mozilla/5.0"},
    )
    response = urlrequest.urlopen(
        request,
        context=ssl.create_default_context(cafile=certifi.where()),
    )
    print(response.code)
except urlrequest.HTTPError as e:
    print(e.code)
except urlrequest.URLError as e:
    print(e.args)
```

What is the output from the first and second test, please? Thanks.

**Comment by xyleme** [comment] 2023-04-27 12:35
Hello Tomas,

here it is:
```

vincent@pc1:~/Bureau$ python test1.py 
(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)'),)
vincent@pc1:~/Bureau$ python test2.py 
200
vincent@pc1:~/Bureau$ 
```

Does this mean that the default SSL context (I understand "the system’s trusted CA certificates") in my case in too restrictive?

**Comment by tmszi** [comment] 2023-04-27 12:59
Hello Vincent,

> Does this mean that the default SSL context (I understand "the system’s trusted CA certificates") in my case in too restrictive?

Thanks. I think that some operating systems (or distributions) have not fresh root certificates or path is not correct, and it is reason why Python 'urlopen' function fail (which is used by g.extension module).

The first test passed in my distribution  (printed is response HTTP code 200 OK success status) without explicit context definition.

**Comment by tmszi** [comment] 2023-04-27 13:05
Could @xyleme try this command  `sudo update-ca-certificates --fresh` and then try running `python test1.py` please?

**Comment by xyleme** [comment] 2023-04-27 13:47
Yes, now it works:
```
vincent@pc1:~/Bureau$ python test1.py 
200
vincent@pc1:~/Bureau$ 
```
From within grass now (after a fresh distclean/upgrade to the latest version), I notice something new with
g.extension. Looks like it's actually retrieving the extension, but fails at installation step:
```
g.extension v.out.ply
------------------------------------------------------------
Reinstalling extension <v.out.ply>...
------------------------------------------------------------

WARNING: Extension <v.out.ply> already installed. Re-installing...
Fetching <v.out.ply> from <https://github.com/OSGeo/grass-addons> (be
patient)...
Traceback (most recent call last):
  File "/usr/local/grass83/scripts/g.extension", line 2876, in <module>
    sys.exit(main())
  File "/usr/local/grass83/scripts/g.extension", line 2856, in main
    install_extension(source=source, url=url, xmlurl=xmlurl, branch=branch)
  File "/usr/local/grass83/scripts/g.extension", line 1239, in install_extension
    ) = install_extension_std_platforms(
  File "/usr/local/grass83/scripts/g.extension", line 2000, in install_extension_std_platforms
    srcdir = download_source_code(
  File "/usr/local/grass83/scripts/g.extension", line 1912, in download_source_code
    directory = download_source_code_official_github(
  File "/usr/local/grass83/scripts/g.extension", line 1778, in download_source_code_official_github
    ga = GitAdapter(
  File "/usr/local/grass83/scripts/g.extension", line 252, in __init__
    self.addons = self._get_addons_list()
  File "/usr/local/grass83/scripts/g.extension", line 387, in _get_addons_list
    addons_dict[file_path.split("/")[3]] = "/".join(
IndexError: list index out of range
ERROR: Unable to process extension:v.out.ply
```

**Comment by tmszi** [comment] 2023-04-27 14:24
> From within grass now (after a fresh distclean/upgrade to the latest version), I notice something new with g.extension. Looks like it's actually retrieving the extension, but fails at installation step:

Installation v.out.ply extension (GRASS GIS 8.3.dev compiled from the main Git branch revision ee3e27166) work for me.

```
GRASS nc_basic_spm_grass7/PERMANENT:grass > g.extension v.out.ply
WARNING: Extension <v.out.ply> already installed. Re-installing...
Fetching <v.out.ply> from <https://github.com/OSGeo/grass-addons> (be
patient)...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 22 (delta 0), reused 11 (delta 0), pack-reused 1
Receiving objects: 100% (22/22), 20.30 KiB | 472.00 KiB/s, done.
Already on 'grass8'
Your branch is up to date with 'origin/grass8'.
Compiling...
Installing...
Updating extensions metadata file...
Updating extension modules metadata file...
Installation of <v.out.ply> successfully finished
```

What is your GRASS GIS revision number, please?

```
GRASS nc_basic_spm_grass7/PERMANENT:grass > g.version -g | grep revision
revision=ee3e27166
```

**Comment by xyleme** [comment] 2023-04-27 15:02
I'm not particularly at ease with git... and I was not compiling the latest revision. After cloning againt the grass-main repo it works fine. I'm very sorry for the trouble.

So I think we can close the topic. Is there a place we could advise users about refreshing CA-certificates in case they encounter the same issue I did?

Sorry again,
Vincent.

**Comment by tmszi** [comment] 2023-04-28 11:03
> So I think we can close the topic. Is there a place we could advise users about refreshing CA-certificates in case they encounter the same issue I did?

We can make it better to catch this exception in the source code and print an appropriate error message and  recommendation what the user should do next.

> Sorry again, Vincent.

It's okay, and it's good that we found out what is the cause of this error and that the issue was reported.

**Closed** 2023-04-29 07:33 UTC
Labels: bug
