### ISSUE TITLE
[Bug] wxGUI: histogram not shown with Python 3.10

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#2046] opened 2021-12-28 18:58 UTC
**Describe the bug**

Loading a raster map and selecting "Analyse map" > "Create histogram of raster map" does not show it:

![image](https://user-images.githubusercontent.com/1295172/147598175-97d4393d-151d-438a-819d-665bcc443cc8.png)

**To Reproduce**

1. Load elevation map
2. Create histogram
3. See plot with missing histogram

**System description (please complete the following information):**

- Operating System: Fedora 35
- affects both G8.0 + G.7.8

```
GRASS version: 7.8.7dev                                                         
Code revision: f9f30f33f                                                        
Build date: 2021-12-14                                                          
Build platform: x86_64-pc-linux-gnu                                             
GDAL: 3.3.2                                                                     
PROJ: 8.2.0                                                                     
GEOS: 3.9.2                                                                     
SQLite: 3.36.0                                                                  
Python: 3.10.1                                                                  
wxPython: 4.0.7                                                                 
Platform: Linux-5.15.6-200.fc35.x86_64-x86_64-with-glibc2.34
```

Note: this is wxPython: 4.0.7-23 (i.e., with multiple recent patches to make the wxGUI start).

**Comment by petrasovaa** [comment] 2021-12-30 04:58
This is basically a duplicate of #2043.

**Comment by petrasovaa** [comment] 2022-01-05 20:15
Closing, see #2043.

**Closed by petrasovaa** 2022-01-05 20:15 UTC
Labels: bug, backport_needed, GUI
