### ISSUE TITLE
g.extension fails to compile/install some addons in Grass 8.0.1 and 8.2.0

### ISSUE THREAD

**Issue by ewCrg** [OSGeo/grass#2472] opened 2022-06-30 23:49 UTC
**Describe the bug**
g.extension and g.extension.all fail to compile/install some (but not all) addons in Grass 8.0.1 and 8.2.0

**To Reproduce**

1. rung g.extension or g.extension.all from gui or console'
2. in g.extension.all window that opens, click reinstall and "force"
3. Returns following error for addons that fail to compile:

```
/usr/bin/ld: cannot open linker script file /builddir/build/BUILD/grass-8.0.1/.package_note-grass-8.0.1-1.fc36.x86_64.ld: No such file or directory
collect2: error: ld returned 1 exit status
make:  [/usr/lib64/grass80//include/Make/Module.make:18: /usr/lib64/grass80/bin/r.accumulate] Error 1
```

**Expected behavior**
should compile and install all addons

**Screenshots**

**System description (please complete the following information):**

- Operating System: Linux Fedora 36
- GRASS GIS version 8.0.1 and 8.2.0 installed from Fedora repository

**Additional context**
This bug had been reported and resolved in a discussion group, and I understood that it had been reported, but I cannot find the bug here or in grass bug tracking.

The problem is resolved in both grass 8.0.1 and grass 8.2 by removing:
`-Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/grass-8.0.1/.package_note-grass-8.0.1-1.fc36.x86_64.ld` from line 78 of `/usr/lib64/grass82/include/Make/Platform.make` (for grass 8.0.1, substitute /grass82/ with /grass80/.

It should not be necessary to change files within distributed rpm's, so this was reported to Redhat Bugzilla. But since this same bug has found its way in two releases of grass, reporting it here as well.

**Comment by tmszi** [comment] 2022-07-01 07:13
Seems there is issue with how to is compile/created package for Fedora GNU/Linux distribution. I tested GRASS GIS version 8.0.2, 8.2.0, 8.3.dev under Gentoo distribution and I can't reproduce any issue (installation/reinstallation some addons e.g. r.accumulate) with `g.extension` and `g.extension.all` module.

**Comment by ewCrg** [comment] 2022-07-01 08:57
Sorry about double posting this bug report. My first attempt at reporting this returned a "page not found" message after clicking on "report bug". I wasn't aware that it had gone through.

I'm sorry also for not leaving the link to the discussion I found the solution in. I didn't have it at the time, but have searched it since and here it is:
https://ask.fedoraproject.org/t/grass-gis-grass-addons-not-compiling/22117

For reference, this is listed as bug 2102895 in Redhat Bugzilla

Also for testing I should have provided a list of the addons that would not compile for me. Here it is:
r.findtheriver
r.quantile.ref
r.hants
r.gdd
r.fuzzy.system
r.univar2
m.gcp.filter
r.out.tiff
v.in.ply
r.regression.series
r.stream.segment
r.resamp.tps
r3.scatterplot
r.crater
r.change.info
r.area
r.colors.contrastbrightness
v.net.salesman.opt
v.label.sa
i.edge
i.wi
r.stream.channel
r.wateroutlet.lessmem
v.surf.mass
i.water
r.scatterplot
r.skyline
r.pi
r.flip
r.series.lwr
v.centerpoint
r.damflood
r.stream.distance
r.fuzzy.logic
i.evapo.senay
r.stream.order
r3.what
r.convergence
r.seasons
i.evapo.zk
r.stream.basins
r.stream.stats
r.stream.snap
v.surf.tps
r.stream.slope
r.massmov
r.soils.texture
r.traveltime
r.surf.idw2
r.vol.dem
v.kriging
r.sim.water.mp
r3.profile
r.hydrodem
v.ellipse
v.area.stats
v.vol.idw
r.fuzzy.set
i.gravity
i.evapo.potrad
r.bitpattern
r.smooth.seg
r.neighborhoodmatrix
r.gwr

**Comment by neteler** [comment] 2022-07-01 09:05
I'd close this report here and continue in
https://bugzilla.redhat.com/show_bug.cgi?id=2102895
since it is a packaging issue due to changes in the Fedora packaging methods.

**Comment by echoix** [comment] 2023-12-22 05:37
The fedora bug is already closed, is it appropriate to close the issue?

**Closed** 2023-12-22 12:18 UTC
Labels: bug, Linux
