### ISSUE TITLE
[Bug] Wrong behaviour of r.external in MS Windows OS

### ISSUE THREAD

**Issue by lluisvicens** [OSGeo/grass#329] opened 2020-02-05 10:49 UTC
**Describe the bug**
I've realized that in a ms-windows environment, the module **r.external** shows an unexpected behavior when linking raster layers with zero values. While in GNU/Linux no matter if you use **r.in.gdal**, **r.import** or **r.external** algorithms to incorporate a raster layer into a mapset, in a windows environment, **r.external** doesn't preserve the original zero values of the layer. 

**To Reproduce**
1. Open GRASS GIS in Windows (location/mapset EPSG:25831)
2. Click on **r.import** to import the raster layer
[layer.zip](https://github.com/OSGeo/grass/files/4158934/layer.zip)
3. Check some stats:
> r.univar map=layer_import@PERMANENT                                             
> total null and non-null cells: 4260096
> total null cells: 4192343
> Of the non-null cells:
> n: 67753
> minimum: 0
> maximum: 10
> range: 10
> mean: 7.80585
> mean of absolute values: 7.80585
> standard deviation: 4.11968
> variance: 16.9718
> variation coefficient: 52.7768 %
> sum: 528870

4. Click on **r.in.gdal** to import the raster layer
[layer.zip](https://github.com/OSGeo/grass/files/4158935/layer.zip)
5. Check some stats:
> r.univar map=layer_gdal@PERMANENT                                               
> total null and non-null cells: 4260096
> total null cells: 4192343
> Of the non-null cells:
> n: 67753
> minimum: 0
> maximum: 10
> range: 10
> mean: 7.80585
> mean of absolute values: 7.80585
> standard deviation: 4.11968
> variance: 16.9718
> variation coefficient: 52.7768 %
> sum: 528870

6. Click on **r.external** to link the raster layer
[layer.zip](https://github.com/OSGeo/grass/files/4158936/layer.zip)
7. Check some stats:
> r.univar map=layer_external@PERMANENT                                           
> total null and non-null cells: 4260096
> total null cells: 4206156
> Of the non-null cells:
> n: 53940
> minimum: 1
> maximum: 10
> range: 9
> mean: 9.80478
> mean of absolute values: 9.80478
> standard deviation: 1.31105
> variance: 1.71884
> variation coefficient: 13.3715 %
> sum: 528870

Note that in **r.external**, the original minimum value (**_0_**) has been converted to **_1_**.

**Expected behavior**
The linked layer should preserve the original values: 0, 10 and null values instead of transforming 0 into 1.

**System description (please complete the following information):**
 - Operating System: Microsoft Windows 10 Enterprise LTSC, Version	10.0.17763 Build 17763
 - GRASS GIS version 7.8.2 (build date 2019-12-11)

**Details about further software components**
> g.version -rge                                                                  
> version=7.8.2
> date=2019
> revision=3900fb114
> build_date=2019-12-11
> build_platform=x86_64-w64-mingw32
> build_off_t_size=8
> libgis_revision=00000
> libgis_date="?"
> proj=6.2.1
> gdal=3.0.2
> geos=3.8.0
> sqlite=3.29.0

**Comment by hellik** [comment] 2020-02-08 15:33
see also https://trac.osgeo.org/grass/ticket/3927

**Comment by hellik** [comment] 2020-02-08 16:24
testing it now with winGRASS master

```
GRASS Version: 7.9.dev                                                          
Code revision: e2d6fdd48                                                        
Build date: 2020-01-07                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.0                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W) 
```
```
D:\wd\testme\layer>gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

```
D:\wd\testme\layer>gdalinfo layer.tif -stats
Driver: GTiff/GeoTIFF
Files: layer.tif
       layer.tif.aux.xml
Size is 2064, 2064
Coordinate System is:
PROJCRS["ETRS89 / UTM zone 31N",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 31N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",3,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Europe - 0°E to 6°E and ETRS89 by country"],
        BBOX[37,0,82.41,6.01]],
    ID["EPSG",25831]]
Data axis to CRS axis mapping: 1,2
Origin = (485835.859600000025239,4651869.459099999628961)
Pixel Size = (2.000950048449587,-2.000949999999775)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  485835.860, 4651869.459) (  2d49'44.12"E, 42d 1' 7.41"N)
Lower Left  (  485835.860, 4647739.498) (  2d49'44.48"E, 41d58'53.50"N)
Upper Right (  489965.820, 4651869.459) (  2d52'43.70"E, 42d 1' 7.64"N)
Lower Right (  489965.820, 4647739.498) (  2d52'43.95"E, 41d58'53.73"N)
Center      (  487900.840, 4649804.479) (  2d51'14.06"E, 42d 0' 0.58"N)
Band 1 Block=2064x1 Type=Float64, ColorInterp=Gray
  Min=0.000 Max=10.000 
  Minimum=0.000, Maximum=10.000, Mean=7.806, StdDev=4.120
  NoData Value=nan
  Metadata:
    STATISTICS_MAXIMUM=10
    STATISTICS_MEAN=7.805853615338
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=4.1196805722052
    STATISTICS_VALID_PERCENT=1.59
```
```
r.in.gdal input=D:\wd\testme\layer\layer.tif output=layer_ringdal 
```

```
g.region -p -a raster=layer_ringdal@testdata align=layer_ringdal@testdata       
projection: 1 (UTM)
zone:       31
datum:      etrs89
ellipsoid:  grs80
north:      4651869.4591
south:      4647739.4983
west:       485835.8596
east:       489965.8205
nsres:      2.00095
ewres:      2.00095005
rows:       2064
cols:       2064
cells:      4260096
(Sat Feb  8 16:56:48 2020)
```

```
r.univar -e map=layer_ringdal@testdata                                          
total null and non-null cells: 4260096
total null cells: 4192343
Of the non-null cells:
----------------------
n: 67753
minimum: 0
maximum: 10
range: 10
mean: 7.80585
mean of absolute values: 7.80585
standard deviation: 4.11968
variance: 16.9718
variation coefficient: 52.7768 %
sum: 528870
1st quartile: 10
median (odd number of cells): 10
3rd quartile: 10
90th percentile: 10

```

```
r.external input=D:\wd\testme\layer\layer.tif output=layerrexternal             
Reading band 1 of 1...
Link to raster map <layerrexternal> created.
```

```
g.region -p -a raster=layerrexternal@testdata align=layerrexternal@testdata     
projection: 1 (UTM)
zone:       31
datum:      etrs89
ellipsoid:  grs80
north:      4651869.4591
south:      4647739.4983
west:       485835.8596
east:       489965.8205
nsres:      2.00095
ewres:      2.00095005
rows:       2064
cols:       2064
cells:      4260096
```

```
r.univar -e map=layerrexternal@testdata                                         
total null and non-null cells: 4260096
total null cells: 4206156
Of the non-null cells:
----------------------
n: 53940
minimum: 1
maximum: 10
range: 9
mean: 9.80478
mean of absolute values: 9.80478
standard deviation: 1.31105
variance: 1.71884
variation coefficient: 13.3715 %
sum: 528870
1st quartile: 10
median (even number of cells): 10
3rd quartile: 10
90th percentile: 10
```

bug also confirmed in winGRASS master.

```
  Min=0.000 Max=10.000 
  Minimum=0.000, Maximum=10.000, Mean=7.806, StdDev=4.120
  NoData Value=nan
```

could it be that _NoData Value=nan_ isn't reckognized?

**Comment by hellik** [comment] 2020-02-08 16:34
changing the no data value now.

```
D:\wd\testme\layer>gdal_translate -a_nodata -9999 layer.tif layer_newnodata.tif
Input file size is 2064, 2064
0...10...20...30...40...50...60...70...80...90...100 - done.
```

```
gdalinfo layer_newnodata.tif -stats
Driver: GTiff/GeoTIFF
Files: layer_newnodata.tif
Size is 2064, 2064
Coordinate System is:
PROJCRS["ETRS89 / UTM zone 31N",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 31N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",3,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Europe - 0°E to 6°E and ETRS89 by country"],
        BBOX[37,0,82.41,6.01]],
    ID["EPSG",25831]]
Data axis to CRS axis mapping: 1,2
Origin = (485835.859600000025239,4651869.459099999628961)
Pixel Size = (2.000950048449587,-2.000949999999775)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  485835.860, 4651869.459) (  2d49'44.12"E, 42d 1' 7.41"N)
Lower Left  (  485835.860, 4647739.498) (  2d49'44.48"E, 41d58'53.50"N)
Upper Right (  489965.820, 4651869.459) (  2d52'43.70"E, 42d 1' 7.64"N)
Lower Right (  489965.820, 4647739.498) (  2d52'43.95"E, 41d58'53.73"N)
Center      (  487900.840, 4649804.479) (  2d51'14.06"E, 42d 0' 0.58"N)
Band 1 Block=2064x1 Type=Float64, ColorInterp=Gray
  Min=0.000 Max=10.000 
  Minimum=0.000, Maximum=10.000, Mean=7.806, StdDev=4.120
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=10
    STATISTICS_MEAN=7.805853615338
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=4.1196805722052
    STATISTICS_VALID_PERCENT=1.59
```
```
r.external input=D:\wd\testme\layer\layer_newnodata.tif output=layer_newnodata_rexternal
Reading band 1 of 1...
Link to raster map <layer_newnodata_rexternal> created.
```

```
g.region -p -a raster=layer_newnodata_rexternal@testdata align=layer_newnodata_rexternal@testdata
projection: 1 (UTM)
zone:       31
datum:      etrs89
ellipsoid:  grs80
north:      4651869.4591
south:      4647739.4983
west:       485835.8596
east:       489965.8205
nsres:      2.00095
ewres:      2.00095005
rows:       2064
cols:       2064
cells:      4260096
```
```
r.univar -e map=layer_newnodata_rexternal@testdata                              
total null and non-null cells: 4260096
total null cells: 4192343
Of the non-null cells:
----------------------
n: 67753
minimum: 0
maximum: 10
range: 10
mean: 7.80585
mean of absolute values: 7.80585
standard deviation: 4.11968
variance: 16.9718
variation coefficient: 52.7768 %
sum: 528870
1st quartile: 10
median (odd number of cells): 10
3rd quartile: 10
90th percentile: 10
```

**Comment by hellik** [comment] 2020-02-08 16:39
```
r.univar -e map=layer_ringdal@testdata                                          
total null and non-null cells: 4260096
total null cells: 4192343
Of the non-null cells:
----------------------
n: 67753
minimum: 0
maximum: 10
```
vs.

```
r.univar -e map=layerrexternal@testdata                                         
total null and non-null cells: 4260096
total null cells: 4206156
Of the non-null cells:
----------------------
n: 53940
minimum: 1
maximum: 10
```
vs.

```
r.univar -e map=layer_newnodata_rexternal@testdata                              
total null and non-null cells: 4260096
total null cells: 4192343
Of the non-null cells:
----------------------
n: 67753
minimum: 0
maximum: 10
```

> could it be that NoData Value=nan isn't reckognized?

it seems to be so as other no data values (e.g. -9999) are reckognized by r.external.

any idea why _NoData Value=nan_ isn't working in winGRASS?

**Comment by hellik** [comment] 2020-02-08 21:29
@rouault any hint why raster linking via gdal in windows does messing up 0 and NaN?

**Comment by metzm** [comment] 2020-02-08 21:34
What are the contents of the file cell_misc/layerrexternal/gdal?

The nodata value of a GDAL linked raster map is obtained at 
https://github.com/OSGeo/grass/blob/master/raster/r.external/link.c#L13
read at
https://github.com/OSGeo/grass/blob/master/lib/raster/gdal.c#L286
and actual cell values are evaluated at
https://github.com/OSGeo/grass/blob/master/lib/raster/get_row.c#L969

For reference, can you use the raster map elev_state_500m from nc_spm_08, post the non-NULL cells: should be 546136.

Then use r.mapcalc to set negative values to 0:
```
g.region -p rast=elev_state_500m
r.mapcalc "myelev_state_500m = if(elev_state_500m < 0, 0, elev_state_500m)"
```
The number of non-NULL cells in myelev_state_500m should still be 546136.

**Comment by hellik** [comment] 2020-02-08 21:55
> What are the contents of the file cell_misc/layerrexternal/gdal?

```
file: D:\wd\testme\layer\layer.tif
band: 1
null: nan
type: 7
```
while clicking in the map display on a nodata value pixel:

```
east, north: 487317.9400288188, 4650438.718240092
layer@testdata: 
  value: No data
```
and on a pixel with a value:

```
east, north: 487858.08281772456, 4650515.110817493
layer@testdata: 
  value: 10
  color: 253:231:037
```

**Comment by hellik** [comment] 2020-02-08 22:04
```
g.region -p -a raster=elev_state_500m@PERMANENT align=elev_state_500m@PERMANENT 
projection: 99 (Lambert Conformal Conic)
zone:       0
datum:      nad83
ellipsoid:  a=6378137 es=0.006694380022900787
north:      318500
south:      -16000
west:       124000
east:       963000
nsres:      500
ewres:      500
rows:       669
cols:       1678
cells:      1122582
```

```
r.univar -e map=elev_state_500m@PERMANENT                                       
total null and non-null cells: 1122582
total null cells: 576446
Of the non-null cells:
----------------------
n: 546136
minimum: -6.68459
maximum: 1952
range: 1958.69
mean: 214.74
mean of absolute values: 214.742
standard deviation: 307.296
variance: 94431.1
variation coefficient: 143.102 %
sum: 117277299.356462
1st quartile: 14.3534
median (even number of cells): 86.3902
3rd quartile: 253.144
90th percentile: 713.306
```
```
r.mapcalc myelev_state_500m = if(elev_state_500m < 0, 0, elev_state_500m)       
(Sat Feb  8 23:03:14 2020) Befehl ausgeführt (0 Sek)
```
```
r.univar -e map=myelev_state_500m@user1                                         
total null and non-null cells: 1122582
total null cells: 576446
Of the non-null cells:
----------------------
n: 546136
minimum: 0
maximum: 1952
range: 1952
mean: 214.741
mean of absolute values: 214.741
standard deviation: 307.296
variance: 94430.6
variation coefficient: 143.1 %
sum: 117277894.444636
1st quartile: 14.3534
median (even number of cells): 86.3902
3rd quartile: 253.144
90th percentile: 713.306
```

**Comment by rouault** [comment] 2020-02-08 22:08
I see https://github.com/OSGeo/grass/blob/70e64a3cb3da5e842d134fc768e0ffbb21b5296a/lib/raster/gdal.c#L292
It would be interesting to see the value of this p string in this case. If it is "nan", then on Windows atof("nan") is like atof("foo") and evaluated to 0.
GDAL in its CPLStrtodDelim() ( https://github.com/OSGeo/gdal/blob/52a25bca3743c9c53ca629999321b4b14193fdf5/gdal/port/cpl_strtod.cpp#L234 ) has hard-coded cases for all those system dependent string representations of non numeric values of floating point values. GRASS could likely use the CPLAtof() function which calls CPLStrodDelim() and is exported

**Comment by hellik** [comment] 2020-02-08 22:21
> r.mapcalc "myelev_state_500m = if(elev_state_500m < 0, 0, elev_state_500m)"

used this for a nc sample data set reference:

```
r.out.gdal input=myelev_state_500m@user1 output=D:\wd\testme\myelev_state_500m.tif format=GTiff
Checking GDAL data type and nodata value...
ERROR 6: SetColorTable() only supported for Byte or UInt16
bands in TIFF format.
Using GDAL data type <Float64>
Die Eingabe-Rasterkarte enthält Zellen mit dem NULL-Wert (no-data). Der Wert -1.#IND wird verwendet, um NoData-Werte in der Eingabekarte zu kennzeichnen. Sie können NoData-Wert mit dem Parameter nodata bestimmen.
Exporting raster data to GTiff format...
r.out.gdal komplett. File <D:\wd\testme\myelev_state_500m.tif> created.

```
```
Driver: GTiff/GeoTIFF
Files: myelev_state_500m.tif
       myelev_state_500m.tif.aux.xml
Size is 1678, 669
Coordinate System is:
PROJCRS["NAD83(HARN) / North Carolina",
    BASEGEOGCRS["NAD83(HARN)",
        DATUM["NAD83 (High Accuracy Reference Network)",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4152]],
    CONVERSION["SPCS83 North Carolina zone (meters)",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",33.75,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",-79,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",36.1666666666667,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",34.3333333333333,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",609601.22,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["USA - North Carolina"],
        BBOX[33.83,-84.33,36.59,-75.38]],
    ID["EPSG",3358]]
Data axis to CRS axis mapping: 1,2
Origin = (124000.000000000000000,318500.000000000000000)
Pixel Size = (500.000000000000000,-500.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_SOFTWARE=GRASS GIS 7.9.dev with GDAL 3.0.4
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  124000.000,  318500.000) ( 84d25'20.59"W, 36d30' 4.87"N)
Lower Left  (  124000.000,  -16000.000) ( 84d13'33.39"W, 33d29'25.98"N)
Upper Right (  963000.000,  318500.000) ( 75d 3' 7.14"W, 36d33'27.20"N)
Lower Right (  963000.000,  -16000.000) ( 75d11'42.51"W, 33d32'41.04"N)
Center      (  543500.000,  151250.000) ( 79d43'30.63"W, 35d 6'40.67"N)
Band 1 Block=1678x1 Type=Float64, ColorInterp=Gray
  Description = myelev_state_500m@user1
  Min=0.000 Max=1952.001 
  Minimum=0.000, Maximum=1952.001, Mean=214.741, StdDev=307.296
  NoData Value=nan
[...]
    STATISTICS_MAXIMUM=1952.0009637576
    STATISTICS_MEAN=214.74118982202
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=307.29564238503
    STATISTICS_VALID_PERCENT=48.65
```

```
r.external input=D:\wd\testme\myelev_state_500m.tif output=myelev_state_500m_rexternal
Reading band 1 of 1...
Link to raster map <myelev_state_500m_rexternal> created.

```
```
file: D:\wd\testme\myelev_state_500m.tif
band: 1
null: nan
type: 7

```

clicking on a no data pixel

```
east, north: 357921.9330855019, 60280.35935563815
myelev_state_500m_rexternal@user1: 
  value: No data
```

clicking on a data pixel

```
east, north: 689571.2515489467, 188157.6827757125
myelev_state_500m_rexternal@user1: 
  value: 43.4359906488
  color: 070:009:092

```
```
r.univar -e map=myelev_state_500m_rexternal@user1                               
total null and non-null cells: 1122582
total null cells: 609042
Of the non-null cells:
----------------------
n: 513540
minimum: 0.000111557
maximum: 1952
range: 1952
mean: 228.371
mean of absolute values: 228.371
standard deviation: 311.948
variance: 97311.6
variation coefficient: 136.597 %
sum: 117277894.444636
1st quartile: 19.8006
median (even number of cells): 102.042
3rd quartile: 265.889
90th percentile: 746.544  
```

**Comment by metzm** [comment] 2020-02-08 22:32
> It would be interesting to see the value of this p string in this case. If it is "nan", then on Windows atof("nan") is like atof("foo") and evaluated to 0.

In this case, Windows atof does not conform to C89 or C99. What about strtod() or sscanf() on Windows? Would any of these recognize nan as nan?

I hope we can solve this problem of recognizing the string "nan" as double nan without the rather complicated GDAL method. Apparently, strtod also does not recognize the string "nan".

**Comment by rouault** [comment] 2020-02-08 23:11
Wine source code which is the best documentation for Microsoft code :-) is interesting in that matter : https://github.com/wine-mirror/wine/commit/8578702e0615341118bb710b47da9c6d869153b9 . It seems that C99 compliance of atof/strtod "nan" is brough by ucrtbase.dll , which is something new to latest versions of Visual Studio and/or Windows 10.
This is complicated by using mingw cross compiler which can links to different CRT : https://sourceforge.net/p/mingw-w64/bugs/501/

**Comment by metzm** [comment] 2020-02-09 16:55
Thanks for the hint Even! It seems that the safest option is to set nan directly for the string "nan". Addressed in PR #338.

**Closed** 2020-02-09 17:05 UTC
Labels: Windows, bug

**Comment by metzm** [comment] 2020-02-09 17:09
Backported to 7.8 in 607d3e1.

**Comment by hellik** [comment] 2020-02-11 17:04
tested with

```
GRASS Version: 7.9.dev                                                          
Code revision: 69524245c                                                        
Build date: 2020-01-10                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.0                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W)  
```

original raster

```
r.univar -e map=myelev_state_500m@user1                                         
total null and non-null cells: 1122582
total null cells: 576446
Of the non-null cells:
----------------------
n: 546136
minimum: 0
maximum: 1952
range: 1952
mean: 214.741
mean of absolute values: 214.741
standard deviation: 307.296
variance: 94430.6
variation coefficient: 143.1 %
sum: 117277894.444636
1st quartile: 14.3534
median (even number of cells): 86.3902
3rd quartile: 253.144
90th percentile: 713.306
```
r.external linked:

```
r.univar -e map=myelev_state_500m_rexternal@user1                               
total null and non-null cells: 1122582
total null cells: 576446
Of the non-null cells:
----------------------
n: 546136
minimum: 0
maximum: 1952
range: 1952
mean: 214.741
mean of absolute values: 214.741
standard deviation: 307.296
variance: 94430.6
variation coefficient: 143.1 %
sum: 117277894.444636
1st quartile: 14.3534
median (even number of cells): 86.3902
3rd quartile: 253.144
90th percentile: 713.306
```
seems to work now.

**Comment by lluisvicens** [comment] 2020-02-12 08:21
Pretty cool! Thanks for your time, efforts, and work on GRASS GIS @hellik @metzm @rouault @neteler
