### ISSUE TITLE
[Bug] r.plus.example addon not available for wingrass 8.5 used in windows tests

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass#3893] opened 2024-06-19 08:31 UTC
## Describe the bug

OSGeo4W Windows tests in CI tests for extensions by fetching extensions for Windows (like r.plus.example) from http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip, which is 404.

## To reproduce
1. https://github.com/OSGeo/grass/actions/runs/9578183044/job/26407881771?pr=3818#step:11:4347
## Screenshots

```
grass.exceptions.CalledModuleError: Module run `g.extension extension=r.plus.example operation=add url=data\sample_modules\r.plus.example prefix=gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <r.plus.example>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_modules.py", line 95, in test_directory_install
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='r.plus.example', operation='add', url='data\\sample_modules\\r.plus.example', prefix='gextension_test_install_path')
Called (Bash): g.extension extension=r.plus.example operation=add url=data\sample_modules\r.plus.example prefix=gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <r.plus.example>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found
``` 

<details><summary>More relevant log section</summary>
<p>

```
Running .\scripts\g.extension\testsuite\test_addons_download.py...
========================================================================
sFsFFF.Fs
======================================================================
FAIL: test_github_download_official_module_src_code_only (__main__.TestModuleDownloadFromDifferentSources.test_github_download_official_module_src_code_only)
Test download extension source code only from official addons
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=db.join operation=add prefix=$GRASS_ADDON_BASE -d` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <db.join>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/db.join.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_download.py", line 181, in test_github_download_official_module_src_code_only
    self.assertModule(gextension)
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='db.join', operation='add', prefix='$GRASS_ADDON_BASE', flags='d')
Called (Bash): g.extension extension=db.join operation=add prefix=$GRASS_ADDON_BASE -d
See the following errors:
Downloading precompiled GRASS Addons <db.join>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/db.join.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_github_install_official (__main__.TestModuleDownloadFromDifferentSources.test_github_install_official)
Test installing C-extension from official addons repository
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=r.gdd operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <r.gdd>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.gdd.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_download.py", line 124, in test_github_install_official
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='r.gdd', operation='add', prefix='D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_download\\gextension_test_install_path')
Called (Bash): g.extension extension=r.gdd operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <r.gdd>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.gdd.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_github_install_official_multimodule (__main__.TestModuleDownloadFromDifferentSources.test_github_install_official_multimodule)
Test installing multi-module extension from official addons repository
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=i.sentinel operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <i.sentinel>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/i.sentinel.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_download.py", line 156, in test_github_install_official_multimodule
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='i.sentinel', operation='add', prefix='D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_download\\gextension_test_install_path')
Called (Bash): g.extension extension=i.sentinel operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <i.sentinel>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/i.sentinel.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_github_install_official_multimodule_and_check_metadata (__main__.TestModuleDownloadFromDifferentSources.test_github_install_official_multimodule_and_check_metadata)
Test installing multi-module extension from official addons
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=i.sentinel operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <i.sentinel>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/i.sentinel.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_download.py", line 230, in test_github_install_official_multimodule_and_check_metadata
    self.assertModule(gextension)
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='i.sentinel', operation='add', prefix='D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_download\\gextension_test_install_path')
Called (Bash): g.extension extension=i.sentinel operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <i.sentinel>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/i.sentinel.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_github_official_module_man_page_src_code_links_exists (__main__.TestModuleDownloadFromDifferentSources.test_github_official_module_man_page_src_code_links_exists)
Test if the installed extension HTML manual page from the
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=db.join operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <db.join>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/db.join.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_download.py", line 199, in test_github_official_module_man_page_src_code_links_exists
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='db.join', operation='add', prefix='D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_download\\gextension_test_install_path')
Called (Bash): g.extension extension=db.join operation=add prefix=testreport\scripts\g.extension\test_addons_download\gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <db.join>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/db.join.zip>: HTTP Error 404: Not Found
----------------------------------------------------------------------
Ran 9 tests in 9.185s
FAILED (failures=5, skipped=3)
========================================================================
FAILED .\scripts\g.extension\testsuite\test_addons_download.py (5 tests failed)
Running .\scripts\g.extension\testsuite\test_addons_modules.py...
========================================================================
FFFFF
======================================================================
FAIL: test_directory_install (__main__.TestModulesFromDifferentSources.test_directory_install)
Test installing extension from directory
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=r.plus.example operation=add url=data\sample_modules\r.plus.example prefix=gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <r.plus.example>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_modules.py", line 95, in test_directory_install
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='r.plus.example', operation='add', url='data\\sample_modules\\r.plus.example', prefix='gextension_test_install_path')
Called (Bash): g.extension extension=r.plus.example operation=add url=data\sample_modules\r.plus.example prefix=gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <r.plus.example>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_remote_targz_without_dir_install (__main__.TestModulesFromDifferentSources.test_remote_targz_without_dir_install)
Test installing extension from (remote) .tar.gz without main dir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=r.plus.example operation=add url=file://testreport\scripts\g.extension\test_addons_modules\data\sample_modules/r.plus.example_sep.tar.gz prefix=gextension_test_install_path --v` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <r.plus.example>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_modules.py", line 118, in test_remote_targz_without_dir_install
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='r.plus.example', operation='add', url='file://D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_modules\\data\\sample_modules/r.plus.example_sep.tar.gz', prefix='gextension_test_install_path', verbose=True)
Called (Bash): g.extension extension=r.plus.example operation=add url=file://testreport\scripts\g.extension\test_addons_modules\data\sample_modules/r.plus.example_sep.tar.gz prefix=gextension_test_install_path --v
See the following errors:
Downloading precompiled GRASS Addons <r.plus.example>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_remote_zip_install (__main__.TestModulesFromDifferentSources.test_remote_zip_install)
Test installing extension from .zip specified by URL (local)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=r.plus.example operation=add url=file://testreport\scripts\g.extension\test_addons_modules\data\sample_modules/r.plus.example.zip prefix=gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <r.plus.example>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_modules.py", line 130, in test_remote_zip_install
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='r.plus.example', operation='add', url='file://D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_modules\\data\\sample_modules/r.plus.example.zip', prefix='gextension_test_install_path')
Called (Bash): g.extension extension=r.plus.example operation=add url=file://testreport\scripts\g.extension\test_addons_modules\data\sample_modules/r.plus.example.zip prefix=gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <r.plus.example>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_targz_install (__main__.TestModulesFromDifferentSources.test_targz_install)
Test installing extension from local .tar.gz
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension extension=r.plus.example operation=add url=data\sample_modules\r.plus.example.tar.gz prefix=gextension_test_install_path` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'Downloading precompiled GRASS Addons <r.plus.example>...\r\nERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_modules.py", line 107, in test_targz_install
    self.assertModule(
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(extension='r.plus.example', operation='add', url='data\\sample_modules\\r.plus.example.tar.gz', prefix='gextension_test_install_path')
Called (Bash): g.extension extension=r.plus.example operation=add url=data\sample_modules\r.plus.example.tar.gz prefix=gextension_test_install_path
See the following errors:
Downloading precompiled GRASS Addons <r.plus.example>...
ERROR: Cannot open URL <http://wingrass.fsv.cvut.cz/grass85/addons/grass-8.5.0dev/r.plus.example.zip>: HTTP Error 404: Not Found
======================================================================
FAIL: test_listing (__main__.TestModulesMetadata.test_listing)
List individual extensions/modules/addons
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension operation=add url=file://testreport\scripts\g.extension\test_addons_modules\data prefix=$GRASS_ADDON_BASE -l` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'ERROR: Cannot open URL </D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_modules\\data>: <urlopen error no host given>\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_modules.py", line 58, in test_listing
    self.assertModule(module)
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(operation='add', url='file://D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_modules\\data', prefix='$GRASS_ADDON_BASE', flags='l')
Called (Bash): g.extension operation=add url=file://testreport\scripts\g.extension\test_addons_modules\data prefix=$GRASS_ADDON_BASE -l
See the following errors:
ERROR: Cannot open URL </testreport\scripts\g.extension\test_addons_modules\data>: <urlopen error no host given>
----------------------------------------------------------------------
Ran 5 tests in 6.682s
FAILED (failures=5)
========================================================================
FAILED .\scripts\g.extension\testsuite\test_addons_modules.py (5 tests failed)
Running .\scripts\g.extension\testsuite\test_addons_toolboxes.py...
========================================================================
F
======================================================================
FAIL: test_listing (__main__.TestToolboxesMetadata.test_listing)
List toolboxes and their content
----------------------------------------------------------------------
Traceback (most recent call last):
  File "etc\python\grass\gunittest\case.py", line 1394, in assertModule
    module.run()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 838, in run
    self.wait()
  File "etc\python\grass\pygrass\modules\interface\module.py", line 859, in wait
    raise CalledModuleError(
grass.exceptions.CalledModuleError: Module run `g.extension operation=add url=file://testreport\scripts\g.extension\test_addons_toolboxes\data prefix=$GRASS_ADDON_BASE -l -t` ended with an error.
The subprocess ended with a non-zero return code: 1. See the following errors:
b'ERROR: Cannot open URL </D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_toolboxes\\data>: <urlopen error no host given>\r\n'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "scripts\g.extension\testsuite\test_addons_toolboxes.py", line 45, in test_listing
    self.assertModule(module)
  File "etc\python\grass\gunittest\case.py", line 1414, in assertModule
    self.fail(self._formatMessage(msg, stdmsg))
AssertionError: Running <g.extension> module ended with non-zero return code (1)
Called (Python): g.extension(operation='add', url='file://D:\\a\\grass\\grass\\testreport\\scripts\\g.extension\\test_addons_toolboxes\\data', prefix='$GRASS_ADDON_BASE', flags='lt')
Called (Bash): g.extension operation=add url=file://testreport\scripts\g.extension\test_addons_toolboxes\data prefix=$GRASS_ADDON_BASE -l -t
See the following errors:
ERROR: Cannot open URL </testreport\scripts\g.extension\test_addons_toolboxes\data>: <urlopen error no host given>
----------------------------------------------------------------------
Ran 1 test in 0.641s
FAILED (failures=1)
========================================================================
FAILED .\scripts\g.extension\testsuite\test_addons_toolboxes.py (1 test failed)
Running .\scripts\g.search.modules\testsuite\test_g_search_modules.py...
========================================================================
.s.F..
======================================================================
FAIL: test_manual_pages (__main__.TestSearchModule.test_manual_pages)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "scripts\g.search.modules\testsuite\test_g_search_modules.py", line 72, in test_manual_pages
    self.assertEqual(len(stdout), 2)
AssertionError: 0 != 2
----------------------------------------------------------------------
Ran 6 tests in 65.545s
FAILED (failures=1, skipped=1)
========================================================================
FAILED .\scripts\g.search.modules\testsuite\test_g_search_modules.py (1 test failed)
``` 

</p>
</details> 

## System description

- Operating System: Windows server 2019 on GitHub Actions CI
- GRASS GIS version: 8.5.0dev on PR https://github.com/OSGeo/grass/pull/3818, but also on main https://github.com/OSGeo/grass/commit/1d31ed26f43ecd6ae916a0e51696186c948b7b10

- details about further software components
    - run `g.version -rge` in a GRASS GIS terminal session or check in
      the GUI menu "Help > About"
    - run `python3 -c "import sys, wx; print(sys.version); print(wx.version())"`
      to print the Python and wxPython version numbers
-->

## Additional context

Wingrass wasn't updated for the switch of main to 8.5dev.

**Comment by echoix** [comment] 2024-06-19 08:32
@hellik I think you're a good fit to look this out.

**Comment by hellik** [comment] 2024-06-19 08:36
We should also ping @landam , as he manages the build server for winGRASS addons.

**Comment by neteler** [comment] 2024-06-19 08:42
> Wingrass wasn't updated for the switch of main to 8.5dev.

This should also go into the "branching how-to" update (see #2963)

**Comment by echoix** [comment] 2024-07-19 22:13
Exactly one month later, here are screenshots showing that tests on windows for extensions still can't be run. It depends on an external server, not managed here by the project, and is left outdated with respect to the development of GRASS. What should we do for the long run? It's not reasonable to rely on something external to us that isn't always available when needed.

![image](https://github.com/user-attachments/assets/15dd3336-27bf-4e51-8767-d43615f47b5e)
![image](https://github.com/user-attachments/assets/c1154e28-e220-4a9a-96cc-dde12e0317ce)
![image](https://github.com/user-attachments/assets/38948753-722c-4cd9-8e3e-258f575c4b80)
![image](https://github.com/user-attachments/assets/84a22a8f-383f-4b89-8444-9cf341e427be)

**Comment by hellik** [comment] 2024-07-20 04:23
@landam any chance to look at it? 

In the long run, would some github action an alternative for building addons?

**Comment by echoix** [comment] 2024-07-20 10:08
For sure, but that location also serves as a repository

**Comment by neteler** [comment] 2024-07-21 08:07
@landam /@pesekon2 can you please create the directories on the wingrass server?

**Comment by landam** [comment] 2024-07-24 09:52
Fixed by https://github.com/landam/wingrass-maintenance-scripts/commit/af891ce041173ba661d78fee251fa7dae59e27a9. Standalone packages + addons are also published for GRASS 8.5: https://wingrass.fsv.cvut.cz/grass85/

**Comment by landam** [comment] 2024-07-24 10:44
> Exactly one month later, here are screenshots showing that tests on windows for extensions still can't be run. It depends on an external server, not managed here by the project, and is left outdated with respect to the development of GRASS. What should we do for the long run? It's not reasonable to rely on something external to us that isn't always available when needed.

@echox You are absolutely right. Rely on external server with limited access is not a good idea. The server and the maintenance scripts (https://github.com/landam/wingrass-maintenance-scripts) where designed a long time ago because there were no regular Windows builds available at all. It was designed as temporary(!) solution (written quickly, no tests available, only bugfixes, no improvements). We definitely need a new well-designed platform to generate GRASS standalone and addons binaries for MS Windows. It must be reliable and manageable by the community.

**Comment by echoix** [comment] 2024-07-24 11:06
> Fixed by https://github.com/landam/wingrass-maintenance-scripts/commit/af891ce041173ba661d78fee251fa7dae59e27a9. Standalone packages + addons are also published for GRASS 8.5: https://wingrass.fsv.cvut.cz/grass85/

Thanks!!

**Comment by echoix** [comment] 2024-07-24 11:07
> It was designed as temporary(!) solution (written quickly, no tests available, only bugfixes, no improvements). 

A proof of the saying: there's nothing more permanent than a temporary solution

**Comment by landam** [comment] 2024-07-26 06:29
@echoix The r.plus.example is still not built (such addon doesn't seem to exist). What need to fixed in order to close this issue?

**Comment by echoix** [comment] 2024-07-26 11:24
Maybe it is part of the test suite (either the code or fetching one not available). But in either case, it wasn't the only one that wasn't able to be fetched, and there was really no 8.5 builds too

**Comment by neteler** [comment] 2024-07-26 13:47
The code is here: `scripts/g.extension/testsuite/data/sample_modules/r.plus.example/`, i.e.

https://github.com/OSGeo/grass/tree/main/scripts/g.extension/testsuite/data/sample_modules/r.plus.example/

**Closed** 2024-07-29 09:51 UTC
Labels: bug, windows, CI
