### ISSUE TITLE
Grass 7.8.5 and 7.9 GUI - exits on first Map window click (i3, cinnamon, lxde on Manjaro)

### ISSUE THREAD

**Issue by kuszinger** [OSGeo/grass#1312] opened 2021-02-07 10:35 UTC
Hello!

Manjaro grass repo version 7.8.5 AUR and also 7.9 from git repo built locally does it.

g.gui starts, maps loaded to the list but with or without that the first click event happens to the map window it disappears. (So it is independent of data content...)
I compiled 7.9 with debug options and grass run with: `g.gisenv set="DEBUG=1"`

However I don't know how to debug what happens to the map window and gui in one. I bet it is python3 runtime in the background...

I've tried to use gdb but as a first time gdber I wasn't able to cache anything.
I've tested on hw running i3, xfc4 and cinnamon. Also Xephyr lxde (to eliminate local HW drivers if I'm doing right)

**What else should I check?**

```
GRASS 7.9.dev (2021)
 ./configure  --with-freetype-includes=/usr/include/freetype2
libgis revision: 94cca3323
libgis date: 2021-02-04T07:32:23+00:00
PROJ: 6.3.2
GDAL/OGR: 3.0.4
GRASS not compiled with GEOS support
SQLite: 3.34.0
```

```
System:    Host: robert-aspire Kernel: 5.11.0-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.1 Desktop: Cinnamon 4.8.6 
           tk: GTK 3.24.24 dm: LightDM Distro: Manjaro Linux 
Graphics:  Device-1: Intel UHD Graphics vendor: Acer Incorporated ALI driver: i915 v: kernel bus ID: 00:02.0 
           chip ID: 8086:9b41 
           Device-2: NVIDIA GP107M [GeForce MX350] vendor: Acer Incorporated ALI driver: nouveau v: kernel bus ID: 01:00.0 
           chip ID: 10de:1c94 
           Device-3: Quanta HD User Facing type: USB driver: uvcvideo bus ID: 1-7:3 chip ID: 0408:a061 
           Display: x11 server: X.Org 1.20.10 driver: loaded: intel,nouveau unloaded: modesetting alternate: fbdev,nv,vesa 
           resolution: 1: 1600x900~60Hz 2: 1680x1050~60Hz s-dpi: 96 
           OpenGL: renderer: Mesa Intel UHD Graphics (CML GT2) v: 4.6 Mesa 20.3.3 direct render: Yes
```

**Comment by petrasovaa** [comment] 2021-02-08 03:46
I suspect this is duplicate of #1123, which is a problem in wxPython.

**Comment by kuszinger** [comment] 2021-02-08 17:58
Fine, that's it!

I'll do the test process as well and join that bug... I'm new here, this one could be closed then... I'll try and thanks for the comment!

**Comment by kuszinger** [comment] 2021-02-08 17:59
OK..... how to close this issue? :) :)

**Comment by kuszinger** [comment] 2021-02-08 18:00
--- > BUG 1123

**Closed** 2021-02-08 17:59 UTC

**Comment by kikislater** [comment] 2021-02-09 09:14
Manjaro user as well : 
https://github.com/OSGeo/grass/issues/1261
