### ISSUE TITLE
[Bug] It is not possible minimize/maximize/resize/move Data Catalog, Layers, Tools pane after the wxGUI quit dialog is closed

### ISSUE THREAD

**Issue by tmszi** [OSGeo/grass#2647] opened 2022-11-14 04:27 UTC
**Describe the bug**
It is not possible minimize/maximize/resize/move Data Catalog, Layers, Tools pane after the wxGUI quit dialog is closed.

**To Reproduce**

1. Launch the wxGUI with single window mode
2. Invoke wxGUI quit dialog by keyboard shortcut Alt + F4 or hit wxGUI window X button
3. Hit Cancel button on the wxGUI quit dialog
4. Try to minimize/maximize/resize/move Data Catalog, Layers, Tools pane

**Expected behavior**
Minimize/maximize/resize/move Data Catalog, Layers, Tools pane should working after the wxGUI quit dialog is closed.

**System description:**

- Operating System: all
- GRASS GIS version: 8.3.dev, 8.2

wxPython:

- 4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5
- 4.2.0 msw (phoenix) wxWidgets 3.2.1

**Additional context**
If wxGUI quit dialog is invoked from the menu File -> Quit GRASS GIS, minimize/maximize/resize/move pane is working.

**Comment by lindakladivova** [comment] 2022-11-22 17:31
@tmszi I looked at that, initially thought that the problem is in event.Veto() missing in **OnCloseWindowOrExit** method in frame/main_window.py . But it looks like that it is not the thing because after adding the event.Veto() and even some refreshing stuff, the problem still persisted... Besides I tried different combinations of refresh functions also with wx.CallAfter/Later. I also tried if the panes are behaving well in terms of attributes and they look good. The last printing I had always ended up in _True_ . It is also interesting that the middle notebook widget does not have any similar problems - works fine.

I also tried to adapt the method OnCloseWindow in python demo/agw/AUI.py accordingly and I came to the same behavior. I think that the problem is that we bind the closing event to wx.Frame and when clicking on Cancel the event somehow damage AUI - panes are partly closed and they do not get to the previous state. I was also trying to add self.Bind(aui.EVT_AUI_PANE_CLOSE, self.OnCloseWindowOrExit) but I also did not success with this. Anyway I would expect that some of the refreshing stuff on the AUI manager could fix the appearance but it did not happen.

I am a bit afraid that it is the thing of agw manager itself, but maybe you could come up with the different solution (I am not so good at event handlings so maybe I missed something). 

I am sending the code I tried (several variants on this but nothing has helped):
  ```

    def OnCloseWindowOrExit(self, event):
        """Cleanup when wxGUI is quitted

        Ask user also to quit GRASS including terminal
        """
        dlg = QuitDialog(self)
        ret = dlg.ShowModal()
        dlg.Destroy()
        if ret != wx.ID_CANCEL:
            self._closeWindow(event)
            if ret == wx.ID_YES:
                self._quitGRASS()
        else:      
            if hasattr(event, "Veto"):
                event.Veto() 
                self.Refresh()
                self.Fit()
                self.Layout()  
                self._auimgr.Update()
                self._auimgr.RefreshCaptions() 
                self._auimgr.Repaint()
                wx.CallAfter(self._auimgr.Update) 
                wx.CallAfter(self._auimgr.RefreshCaptions)   
                wx.CallAfter(self._auimgr.Repaint)  
                wx.CallLater(500, self._auimgr.Update)  
                wx.CallLater(500, self._auimgr.RefreshCaptions)
                wx.CallLater(500, self._auimgr.Repaint)
                
                nbpanes = self._auimgr.GetAllPanes()
                for pane in nbpanes:
                    print(pane)
                    print(pane.IsShown())
                    print(pane.IsMovable())
                    print(pane.IsFloatable())
                    print(pane.IsOk())
                return
```

**Comment by petrasovaa** [comment] 2022-11-24 04:51
I agree this looks like problem in wx.lib.agw.aui, specifically showing a dialog within a close event handler. I think we should probably report this as an issue, I couldn't find any solution to this.

**Comment by tmszi** [comment] 2022-11-24 08:29
Check the wxPython demo AUI_DockingWindowMgr.py which use same `wx.EVT_CLOSE` event handler, please.

Simple example:

**A. wxGUI singe window mode**

1. Try comment `wx.EVT_CLOSE` event handler `OnCloseWindowOrExit(self, event)` method content (print some info text):

```python
    def OnCloseWindowOrExit(self, event):
        """Cleanup when wxGUI is quitted

        Ask user also to quit GRASS including terminal
        """
        print("Close event handler")
        # dlg = QuitDialog(self)
        # ret = dlg.ShowModal()
        # dlg.Destroy()
        # if ret != wx.ID_CANCEL:
        #     self._closeWindow(event)
        #     if ret == wx.ID_YES:
        #         self._quitGRASS()
```
2.  Launch wxGUI with single window mode
3.  Close wxGUI window by keyboard shortcut Alt + F4 or by hit window X button
4. "Close event handler" text was printed inside to the wxGUI Console page (tab)
5.  Minimize/maximize/resize/move Data Catalog, Layers, Tools pane **is not working**

**B. wxPython demo** AUI_DockingWindowMgr.py file

1. Try comment `wx.EVT_CLOSE` event handler `OnClose(self, event)` method content (print some info text):

```python
    def OnClose(self, event):
        print("Close event handler")
        # self._mgr.UnInit()
        # del self._mgr
        # self.Destroy()
```
2.  Launch AUI_DockingWindowMgr.py `python AUI_DockingWindowMgr.py` and hit Show the aui Demo Frame button
3.  Close aui Demo window by keyboard shortcut Alt + F4 or by hit window X button
4. "Close event handler" text was printed inside the emulator terminal
5.  Minimize/maximize/resize/move Tree, Text pane **is working**

The question is, what difference in aui manager initialization and usage or something else between wxPython aui demo and wxGUI single-window mode causes minimize/maximize/resize/move Data Catalog, Layers, Tools pane not to work after invoking `wx.EVT.CLOSE` event?

**Comment by petrasovaa** [comment] 2022-11-27 03:35
> The question is, what difference in aui manager initialization and usage or something else between wxPython aui demo and wxGUI single-window mode causes minimize/maximize/resize/move Data Catalog, Layers, Tools pane not to work after invoking `wx.EVT.CLOSE` event?

The aui demo you are referring to is not the Python-based wx.lib.agw.aui we are using. If you try that one it has the same issue.

**Comment by tmszi** [comment] 2022-11-27 03:45
> The aui demo you are referring to is not the Python-based wx.lib.agw.aui we are using. If you try that one it has the same issue.

Yes, you are right, I overlooked that it is the agw library `python AUI.py`.

**Comment by petrasovaa** [comment] 2023-09-22 03:04
See https://github.com/wxWidgets/Phoenix/issues/2313

**Comment by tmszi** [comment] 2023-09-22 06:24
PR https://github.com/wxWidgets/Phoenix/pull/2460

**Comment by petrasovaa** [comment] 2023-09-22 13:13
> PR [wxWidgets/Phoenix#2460](https://github.com/wxWidgets/Phoenix/pull/2460)

Thanks! Looks good to me, any idea for a workaround on our side before this gets merged and released?

**Comment by tmszi** [comment] 2023-09-22 19:21
> Thanks! Looks good to me, any idea for a workaround on our side before this gets merged and released?

PR #3177

**Closed** 2023-09-26 11:41 UTC
Labels: bug, GUI
