### ISSUE TITLE
[Bug] wxGUI nviz: map is no longer centered in the window

### ISSUE THREAD

**Issue by cmbarton** [OSGeo/grass#590] opened 2020-05-05 18:29 UTC
**Describe the bug**
When 3D view (nviz) is launched, the map is no longer centered in the window, but extends off the view to the upper right. It is very difficult to view all the map. Pan doesn't work until the tilt tool is used. 

**To Reproduce**
Open elevation map in NC demo data
Zoom to map to make sure it's all in the 2D view
Switch to 3D view
Map is mostly out of the view now

**Expected behavior**
Map should be centered in the view window when 3D mode is launched

**Screenshots**
![nviz_screenshot](https://user-images.githubusercontent.com/8967599/81101861-9521ab00-8ec3-11ea-86e8-d1c3ceff8f78.jpg)

**System description (please complete the following information):**

- Mac OSX 10.14
- GRASS GIS version 7.8.3 downloaded and compiled 5 May 2020

**Comment by neteler** [comment] 2020-05-05 19:44
I can confirm this on Fedora.

**Comment by petrasovaa** [comment] 2020-05-06 02:52
I can't reproduce this in master, can you test master? Does your region match the map?

**Comment by nilason** [comment] 2020-05-06 10:51
I can reproduce it with master too, with and without extra (second) monitor (region is set with the dem file).

Python 3.7.7
wx.version() = 4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5

![grass_#590](https://user-images.githubusercontent.com/14186207/81167577-b94dbc80-8f95-11ea-9ab5-c26233e3ce01.gif)

Log from immediately before switching to 3D mode:
```
$ g.gisenv set=WX_DEBUG=1

GRASS 7.9.dev (nc_spm_08_grass7):/Volumes/dev/grass > GUI D1/1: MapFrame.GetLayerManager(): Method GetLayerManager isdepreciated, use some general approach instead such as Signals or giface
GUI D1/1: MapFrame.GetLayerManager(): Method GetLayerManager isdepreciated, use some general approach instead such as Signals or giface
GUI D1/1: RenderMapMgr.Abort()
GUI D1/1: RenderLayerMgr(d.rast map=elev_lid792_1m@PERMANENT).Abort()
GUI D1/1: gcmd.RunCommand(): g.region -ugpc3
GUI D1/1: gcmd.RunCommand(): get return code 0 (0.038948 sec)
GUI D1/1: Nviz::Nviz()
GUI D1/1: FloatSlider.__init__()
GUI D1/1: FloatSlider.__init__()
GUI D1/1: FloatSlider.__init__()
GUI D1/1: FloatSlider.__init__()
GUI D1/1: FloatSlider.__init__()
GUI D1/1: GLCanvas.OnPaint()
GUI D1/1: Nviz::InitView()
GUI D1/1: Nviz::LoadRaster(): name=elev_lid792_1m@PERMANENT -> id=110658
GUI D1/1: GLWindow.LoadDataLayers(): time = 0.127216
GUI D1/1: GLWindow.UnloadDataLayers(): time = 0.000002
GUI D1/1: Nviz::SetViewDefault(): hdef=478.764282, hmin=-1396.235718, hmax=2353.764160
GUI D1/1: NvizToolWindow.UpdatePage(): view
GUI D1/1: NvizToolWindow.UpdatePage(): light
GUI D1/1: NvizToolWindow.UpdatePage(): cplane
GUI D1/1: NvizToolWindow.UpdatePage(): decoration
GUI D1/1: NvizToolWindow.UpdatePage(): animation
GUI D1/1: NvizToolWindow.UpdatePage(): surface
GUI D1/1: NvizToolWindow.UpdatePage(): fringe
GUI D1/1: RenderMapMgr.Render(): 0 layers to be rendered (force=1, all active layers -> 0)
GUI D1/1: RenderMapMgr.OnRenderDone() time=0.000335 sec (comp: 0.000001)
GUI D1/1: BufferedWindow.UpdateMap(): finished
GUI D1/1: gcmd.RunCommand(): g.region -ugpc
GUI D1/1: gcmd.RunCommand(): get return code 0 (0.038057 sec)
GUI D1/1: GLCanvas.OnPaint()
GUI D1/1: GLWindow.LoadDataLayers(): time = 0.000008
GUI D1/1: GLWindow.UnloadDataLayers(): time = 0.000003
GUI D1/1: BufferedWindow.UpdateMap(): started (render=True, renderVector=True)
GUI D1/1: RenderLayerMgr.Render(d.rast map=elev_lid792_1m@PERMANENT): force=1 img=/var/folders/k4/xy86sh0n0tb3fyjl15kp0ttc0000gn/T/grass7-nila-41063/tmph5p2mptn.ppm
GUI D1/1: RenderMapMgr.Render(): 1 layers to be rendered (force=1, all active layers -> 1)
GUI D1/1: RenderLayerMgr.OnRenderDone(d.rast map=elev_lid792_1m@PERMANENT): err=None time=0.276615
GUI D1/1: gcmd.RunCommand(): g.pnmcomp --o input=/var/folders/k4/xy86sh0n0tb3fyjl15kp0ttc0000gn/T/grass7-nila-41063/tmph5p2mptn.ppm mask=/var/folders/k4/xy86sh0n0tb3fyjl15kp0ttc0000gn/T/grass7-nila-41063/tmph5p2mptn.pgm opacity=1.0 bgcolor=255:255:255 width=825 height=622 output=/var/folders/k4/xy86sh0n0tb3fyjl15kp0ttc0000gn/T/grass7-nila-41063/tmp3equkal_.ppm
GUI D1/1: gcmd.RunCommand(): get return code 0 (0.041670 sec)
GUI D1/1: RenderMapMgr.OnRenderDone() time=0.320350 sec (comp: 0.041930)
GUI D1/1: BufferedWindow.UpdateMap(): finished
GUI D1/1: gcmd.RunCommand(): g.region -ugpc
GUI D1/1: gcmd.RunCommand(): get return code 0 (0.044095 sec)
GUI D1/1: GLCanvas.OnPaint()
GUI D1/1: GLWindow.LoadDataLayers(): time = 0.000006
GUI D1/1: GLWindow.UnloadDataLayers(): time = 0.000002

GRASS 7.9.dev (nc_spm_08_grass7):/Volumes/dev/grass > g.region -p
projection: 99 (Lambert Conformal Conic)
zone:       0
datum:      nad83
ellipsoid:  a=6378137 es=0.006694380022900787
north:      220750
south:      220000
west:       638300
east:       639000
nsres:      1
ewres:      1
rows:       750
cols:       700
cells:      525000

```

**Comment by petrasovaa** [comment] 2020-05-19 20:00
I tested it (7.8.3) on virtual machines Windows VM and Mac OS 10.15, and I can't reproduce the problem. I wonder if it has something to do with OpenGL version or hardware, especially because I am not aware of any changes related to this. Perhaps you could test the wxPython OpenGL demo and see if it behaves correctly.

**Comment by nilason** [comment] 2020-05-19 20:31
If you mean the one titled "GLCanvas", it seems to behave correctly.

**Comment by nilason** [comment] 2020-05-19 21:09
Overlooked the console again:

```
Traceback (most recent call last):
  File "/usr/local/grass79/gui/wxpython/nviz/tools.py", line
3247, in OnSetRaster

self.UpdateSurfacePage(layer, data, updateName=False)
  File "/usr/local/grass79/gui/wxpython/nviz/tools.py", line
5370, in UpdateSurfacePage

self.OnSurfaceAxis(None)
  File "/usr/local/grass79/gui/wxpython/nviz/tools.py", line
3784, in OnSurfaceAxis

id = data['surface']['object']['id']
KeyError
:
'object'
```

on switching to 3D view.

**Comment by petrasovaa** [comment] 2020-05-19 23:42
This error wouldn't cause the described issue. I am little bit stuck here since I can't reproduce it and I don't even have a good idea what to try.

**Comment by hmitaso** [comment] 2020-05-21 04:17
I can confirm the issue too. I have Mac 10.12.6 with GRASS7.6.2dev where nviz works and I tested nviz with GRASS7.8.3 and 7.9 (all binaries are from Michael) and nviz has wrong center which makes it practically unuseable. It seems that it puts the center at the corner (you can see it when using the top view option and zoom out with perspective). However, when I save the image, it is positioned correctly and m.nviz... works too (I tried it from GUI). "Center" button keeps the wrong center and "look here" works to some extent although it seems to be misaligned.  Below is a screenshot of the display and the saved image from the exact same display (this is elevation from the NC dataset) - the default view and top view

![viewstartdefault](https://user-images.githubusercontent.com/10482546/82522573-de930c80-9af7-11ea-8127-a5f0c4f9cf08.jpg)

<img width="911" alt="viewstartdefault_screenshot" src="https://user-images.githubusercontent.com/10482546/82522521-b6a3a900-9af7-11ea-9388-86416a67113b.png"> 

<img width="911" alt="view_top_maxperspective_screenshot" src="https://user-images.githubusercontent.com/10482546/82522651-139f5f00-9af8-11ea-9714-4280bc6f9b43.png">
![view_top_maxperspective](https://user-images.githubusercontent.com/10482546/82522673-2154e480-9af8-11ea-8d2d-9588cd00009c.jpg)

I can try to update the system to 10.15 to see whether it will help but we may need to make 10.15 a requirement then.

**Comment by petrasovaa** [comment] 2020-05-21 15:12
The only change I am aware of is #307. Could you let me know what this gives you? Run it from Layer Manager Python console:
```
>>> import wx
>>> wx.GetTopLevelWindows()[0].GetContentScaleFactor()
```

**Comment by cmbarton** [comment] 2020-05-21 17:17
Also maybe a change in the way something in wxPython works? It looks like the image is defaulting to center the LL corner rather than the center of the image. Might need to do some calculations to find the center and then reposition it initially in the window.

**Comment by nilason** [comment] 2020-05-21 17:56
```
>>> import wx
>>> wx.GetTopLevelWindows()[0].GetContentScaleFactor()
2.0
```

**Comment by nilason** [comment] 2020-05-21 18:02
> The only change I am aware of is #307.

I think the problem predates that PR/commit. But it might somehow be related to HiDPI monitors, given that one (seemingly precisely) quarter of the scene is displayed.

**Comment by petrasovaa** [comment] 2020-05-21 18:42
Could you possibly revert those changes locally and test that? I am getting pretty sure it must be related. If that's the case, I don't know what should be done, because it seems to be fixing issues for some cases (my hires screen with 200% scaling needed this) and breaking others.

**Comment by nilason** [comment] 2020-05-22 07:24
> Could you possibly revert those changes locally and test that?

Indeed, the changes of #307 introduced this issue. After reverting that commit it works as expected. At least we now know roughly the cause of this... only remains to find a solution :).

**Comment by mlennert** [comment] 2020-05-22 08:14
Am 22. Mai 2020 09:25:01 MESZ schrieb nilason <notifications@github.com>:
>> Could you possibly revert those changes locally and test that?
>
>Indeed, the changes of #307 introduced this issue. After reverting that
>commit it works as expected. At least we now know roughly the cause of
>this... only remains to find a solution :).


Maybe some hints to MacOS specific issues here:

https://groups.google.com/forum/m/#!msg/wx-users/GEWSNxvhv30/Zf5zNg9_CgAJ

?

**Comment by nilason** [comment] 2020-05-22 09:19
In: https://github.com/OSGeo/grass/blob/dc3c4c722805e8a19c02ca86ce8f5ea8c956a5b0/gui/wxpython/nviz/mapwindow.py#L408

replacing `self.GetContentScaleFactor()` with `1`, solves the problem on my machine.

**Comment by nilason** [comment] 2020-05-22 09:22
> In:
> 
> https://github.com/OSGeo/grass/blob/dc3c4c722805e8a19c02ca86ce8f5ea8c956a5b0/gui/wxpython/nviz/mapwindow.py#L408
> 
> replacing `self.GetContentScaleFactor()` with `1`, solves the problem on my machine.

@neteler Is this also true for the Fedora case?

**Comment by petrasovaa** [comment] 2020-05-22 14:22
Yes, the scale factor it is used for multiplication, so using 1 obviously fixes the problem. But not using the scale factor was breaking my setup with high res screen. In case of Mac I suspect the retina screen is the problem here, since I tested mac in VM with normal screen and everything worked. Why Fedora is having these issues I don't know. Could you all please give me a list of your:

- OS
- wx version
- GRASS version
- display setup description (nothing special, retina, hires, scaling on) 
- output of `wx.GetTopLevelWindows()[0].GetContentScaleFactor()` from GRASS Python console (see above)

**Comment by nilason** [comment] 2020-05-22 15:27
Using 1 was absolutely not a suggestion for a fix, only description of what happens...

Tested on 7.9.dev (a31d3204a):

- macOS 10.14.6
- 4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5
- 2560 x 1600 px (227 ppi)
- 1680 x 1050 px (~100 ppi, secondary)

If the Layer Manager is located on the hi-res display, the scale factor is 2 but if it is located on the "standard" display it is 1.

If scale factor is 2 then the problem occurs.

**Comment by isaacullah** [comment] 2020-06-01 21:11
Can confirm this issue on Ubuntu 20.04 and GRASS 7.8.3. Every time you switch between 2D and back to 3D the map is now decentered and it appears blank. You have to click the "reset" button to get the map back centered in the 3D view. This happens even if you do not zoom or pan the map in either view, but just switch back and forth a couple of times.

**Comment by petrasovaa** [comment] 2020-06-02 02:07
> Can confirm this issue on Ubuntu 20.04 and GRASS 7.8.3. Every time you switch between 2D and back to 3D the map is now decentered and it appears blank. You have to click the "reset" button to get the map back centered in the 3D view. This happens even if you do not zoom or pan the map in either view, but just switch back and forth a couple of times.

This is something different, please create a new ticket. Also please add any errors in console.

**Comment by petrasovaa** [comment] 2020-07-08 18:38
> Yes, the scale factor it is used for multiplication, so using 1 obviously fixes the problem. But not using the scale factor was breaking my setup with high res screen. In case of Mac I suspect the retina screen is the problem here, since I tested mac in VM with normal screen and everything worked. Why Fedora is having these issues I don't know. Could you all please give me a list of your:
> 
> * OS
> * wx version
> * GRASS version
> * display setup description (nothing special, retina, hires, scaling on)
> * output of `wx.GetTopLevelWindows()[0].GetContentScaleFactor()` from GRASS Python console (see above)

@neteler could you please provide this info since you confirmed this issue?

**Comment by neteler** [comment] 2020-07-12 20:28
I tried today with G78, and the display was centered (maybe the issue vanished on Fedora? Or only happens with a second monitor?)

My system:

* Fedora 32
* python3-wxpython4-4.0.7-5.fc32.x86_64
* display: nothing special (maybe the other time I had a second monitor attached to my laptop; due to travelling I cannot test that now)
* output of `wx.GetTopLevelWindows()[0].GetContentScaleFactor()` from GRASS Python console:

```
import wx
wx.GetTopLevelWindows()[0].GetContentScaleFactor()
1.0
```

**Comment by petrasovaa** [comment] 2020-07-13 03:36
> I tried today with G78, and the display was centered (maybe the issue vanished on Fedora? Or only happens with a second monitor?)
> * display: nothing special (maybe the other time I had a second monitor attached to my laptop; due to travelling I cannot test that now)

Thanks, yes, the high res screen is the problem.

**Comment by petrasovaa** [comment] 2020-07-13 03:41
> Tested on 7.9.dev ([a31d320](https://github.com/OSGeo/grass/commit/a31d3204a950d2ce36e4c1aa78616e05a50f9add)):
> 
> * macOS 10.14.6
> * 4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5
> * 2560 x 1600 px (227 ppi)
> * 1680 x 1050 px (~100 ppi, secondary)
> 
> If the Layer Manager is located on the hi-res display, the scale factor is 2 but if it is located on the "standard" display it is 1.
> 
> If scale factor is 2 then the problem occurs.

@nilason, could you possibly test it with newest wxPython 4.1.0? Also it would be useful to test the 4.1.0 opengl wx demo since it incorporates the GetContentScaleFactor unlike the 4.0.7 version.

**Comment by nilason** [comment] 2020-07-13 10:26
> @nilason, could you possibly test it with newest wxPython 4.1.0? Also it would be useful to test the 4.1.0 opengl wx demo since it incorporates the GetContentScaleFactor unlike the 4.0.7 version.



With current master and Python 3.7.3 + wxPython 4.1.0 osx-cocoa (phoenix) wxWidgets 3.1.4 I didn't get so far, switching to 3D mode failed with following traceback:

```
Starting 3D view mode...                                                        
Traceback (most recent call last):
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/gui/wxpython/mapdisp/toolbars.py", line 244, in
OnSelectTool

self.parent.AddNviz()
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/gui/wxpython/mapdisp/frame.py", line 399, in
AddNviz

self.starting3dMode.emit(firstTime=True)
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/etc/python/grass/pydispatch/signal.py", line
229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/etc/python/grass/pydispatch/dispatcher.py",
line 349, in send

**named
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/etc/python/grass/pydispatch/robustapply.py",
line 60, in robustApply

return receiver(*arguments, **named)
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/gui/wxpython/lmgr/frame.py", line 446, in
AddNvizTools

display=self.GetMapDisplay())
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/gui/wxpython/nviz/tools.py", line 106, in
__init__

self.AddPage(page=self._createAnimationPage(),
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/gui/wxpython/nviz/tools.py", line 521, in
_createAnimationPage

usage="record", label=_("Record"))
  File "/Volumes/dev/grass/dist.x86_64-apple-
darwin19.5.0/gui/wxpython/gui_core/widgets.py", line 503, in
__init__

buffer.SetMaskColour(maskColor)
wx._core
.
wxAssertionError
:
C++ assertion "m_rawAccessCount == 1" failed at
/Users/robind/projects/bb2/dist-osx-
py37/build/ext/wxWidgets/src/osx/core/bitmap.cpp(419) in
EndRawAccess():
```

When I find the time I'll look into it, I'll put up a PR and/or Issue, if you don't already have a hunch...

**Comment by petrasovaa** [comment] 2020-07-13 15:01
Hmm, not really, it seems OS specific. Try GenericButtons demo if it works. Also try to not call `buffer.SetMaskColour(maskColor)` line 503 in gui_core/widgets.py. If I can't figure out anything, I will just change these fancy buttons into the standard ones and that will solve it.

**Comment by nilason** [comment] 2020-07-13 15:12
> Also try to not call buffer.SetMaskColour(maskColor) line 503 in gui_core/widgets.py.

I commented out that line and it the centring did work. It seems this issue is resolved with wxPython 4.1.0.
I had no problem with wxdemo generic buttons.

**Comment by petrasovaa** [comment] 2020-07-13 17:09
> > Also try to not call buffer.SetMaskColour(maskColor) line 503 in gui_core/widgets.py.
> 
> I commented out that line and it the centring did work. It seems this issue is resolved with wxPython 4.1.0.

Just to clarify this, it works with 4.1.0 with your high-res screen? Is the scale factor 1 or 2?

> I had no problem with wxdemo generic buttons.

I will look at that later today.

**Comment by nilason** [comment] 2020-07-13 17:20
> Just to clarify this, it works with 4.1.0 with your high-res screen? Is the scale factor 1 or 2?

Yes, and scale factor is 2.
At the moment I can't test on standard res screen (but there was no problem with that one).

> I will look at that later today.

Great, thanks!

**Comment by neteler** [comment] 2020-07-20 21:07
> > I tried today with G78, and the display was centered (maybe the issue vanished on Fedora? Or only happens with a second monitor?)
> > 
> > * display: nothing special (maybe the other time I had a second monitor attached to my laptop; due to travelling I cannot test that now)
> 
> Thanks, yes, the high res screen is the problem.

Back to my laptop-with-external-monitor setup:

```
GRASS 7.9.dev (nc_spm_08_grass7):~ > xrandr --listmonitors
Monitors: 2
 0: +*eDP-1 1920/276x1080/155+0+0  eDP-1
 1: +HDMI-2 1920/518x1200/324+1920+0  HDMI-2


wx.GetTopLevelWindows()[0].GetContentScaleFactor()
1.0
```

**Comment by petrasovaa** [comment] 2020-07-21 01:46
> Back to my laptop-with-external-monitor setup:
> 
> ```
> GRASS 7.9.dev (nc_spm_08_grass7):~ > xrandr --listmonitors
> Monitors: 2
>  0: +*eDP-1 1920/276x1080/155+0+0  eDP-1
>  1: +HDMI-2 1920/518x1200/324+1920+0  HDMI-2
> 
> 
> wx.GetTopLevelWindows()[0].GetContentScaleFactor()
> 1.0
> ```

That looks normal, are you saying the bug shows up in this case? On which screen?

**Comment by neteler** [comment] 2020-07-22 18:58
I tested this now, starting the GUI first on one, then (after closing) on the second screen: all fine, no (more) problem. Somehow it vanished on my laptop, perhaps thanks to one of the massive wxGUI improvements of the last weeks.

So, now maybe a mac-only issue?

**Closed** 2020-08-12 13:46 UTC
Labels: bug
