### ISSUE TITLE
g.extension failing in GRASS 7.8.5

### ISSUE THREAD

**Issue by micha-silver** [OSGeo/grass#1798] opened 2021-08-16 09:04 UTC
**Describe the bug**
Running `g.extension` to add an add-on fails with:

```
micha@RMS:~$ g.extension v.surf.tps
Fetching <v.surf.tps> from GRASS GIS Addons repository (be patient)...
svn: E170000: URL 'https://github.com/OSGeo/grass-addons/trunk/grass7/vector/v.surf.tps' doesn't exist
ERROR: GRASS Addons <v.surf.tps> not found
micha@RMS:~$ g.version
GRASS 7.8.5 (2020)
```

See also: https://gis.stackexchange.com/questions/408345/installing-grass-extension-modules-on-macos-and-linux

**To Reproduce**

1. `g.extension -l` works as expected
2. g.extension <addon_module_name> fails

**Expected behavior**
Download addon script from the correct github path.

**System description (please complete the following information):**

- Operating System: Linux, .
- GRASS GIS version [e.g. 7.8.5]

**Additional context**
Currently in the `g.extension` python script, the function:
`def resolve_source_code(url=None, name=None, branch=None):`
defaults to the git path `grass-addons/trunk/`:
```
   if not url and name:
        module_class = get_module_class_name(name)
        # note: 'trunk' is required to make URL usable for 'svn export' call
        git_url = 'https://github.com/OSGeo/grass-addons/trunk/' \
                   'grass{version}/{module_class}/{module_name}' \
                   .format(version=version[0],
                           module_class=module_class, module_name=name)
        # trac_url = 'https://trac.osgeo.org/grass/browser/grass-addons/' \
        #            'grass{version}/{module_class}/{module_name}?format=zip' \
        #            .format(version=version[0],
        #                    module_class=module_class, module_name=name)
        # return 'official', trac_url
        return 'official', git_url
```
Perhaps this is the cause of the error?

**Comment by ninsbl** [comment] 2021-08-16 12:13
See: https://grass.osgeo.org/news/2021_08_01_g_extension_currently_not_working/

And:
https://github.com/OSGeo/grass/pull/1762

The issue is addressed and updated binaries are hopefully available soon (the RC needs to be aprooved to be final).

**Comment by micha-silver** [comment] 2021-08-16 12:17
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Thanks!
    
    
    On 8/16/21 3:13 PM, Stefan Blumentrath
      wrote:
    
    
      
      See: https://grass.osgeo.org/news/2021_08_01_g_extension_currently_not_working/
      And:
        #1762
      The issue is addressed and updated binaries are hopefully
        available soon (the RC needs to be aprooved to be final).
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OSGeo/grass/issues/1798#issuecomment-899461754",
"url": "https://github.com/OSGeo/grass/issues/1798#issuecomment-899461754",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    -- 
Micha Silver
Ben Gurion Univ.
Sde Boker, Remote Sensing Lab
cell: +972-523-665918
https://orcid.org/0000-0002-1128-1325

**Comment by metzm** [comment] 2021-08-16 19:14
That means users who installed GRASS through their distro's package manager have to wait until an updated version is available with their distro's package manager? Until then (can take a while) they are not able to install GRASS addons via `g.extension` any more?
This can't be true, there must be a mechanism to support installation of GRASS addons at least with the latest minor version of GRASS (7.8.x)?!?

**Comment by veroandreo** [comment] 2021-08-16 20:49
> That means users who installed GRASS through their distro's package manager have to wait until an updated version is available with their distro's package manager? Until then (can take a while) they are not able to install GRASS addons via `g.extension` any more?

Well, to some, there's the option of downloading the zip file and installing that. Not sure though if this works for all addons and all OSs. But, basically yes. 

We have now GRASS 7.8.6 RC2 available for testing but I'm not sure if RCs reach distro's package managers. 
We cannot create binaries for windows because osgeo4w changed from version 1 to 2. @ninsbl is tirelessly working on setting that up (#1683). 
For mac users, @cmbarton already uploaded the packages here: http://grassmac.wikidot.com/downloads

**Comment by veroandreo** [comment] 2021-09-14 22:47
The fix to g.extension was applied, backported and `g.extension` works in releasebranch, can we close this one?

**Comment by HuidaeCho** [comment] 2021-09-30 14:23
> there must be a mechanism to support installation of GRASS addons at least with the latest minor version of GRASS (7.8.x)?!?

Totally agreed, but it can be tricky to support custom/distro installations because of DLL dependencies... I do have my own compiled binaries and cannot install addons :-(.

**Comment by landam** [comment] 2021-10-10 14:19
With 7.8.6 release the issue is solved. Feel free to re-open if needed.

**Closed by landam** 2021-10-10 14:19 UTC
Labels: bug
