### ISSUE TITLE
[Bug] v.dissolve looses connection with database tables when running

### ISSUE THREAD

**Issue by geografin** [OSGeo/grass#3420] opened 2024-02-13 12:27 UTC
**Describe the bug**
When processing the vector map one of backend commands (seems to be v.reclass) change the database table name to map_somenumbersandchars (example map_ef0691c223f2_631@PERMANENT), after that following command (v.extract) can't find tables for the map.

**To Reproduce**

1. Take a vector with varchar column with duplicated values and several columns with double precision or integer values.
2. Start dissolving this vector on varchar column  v.dissolve (version grass 8.4) (aggregate_backend=sql)
3. See error ERROR: There is no table connected to <map>

**Expected behavior**
A dissolved map should be written.

**System description:**

- Operating System: Docker with GRASS GIS (debian)
- GRASS GIS version 8.4.0

**Comment by ecodiv** [comment] 2024-02-13 13:08
@geografin I can't reproduce the problem on GRASS 8.4.0 on Ubuntu 22.04, using aggregate_backend=sql.

**Comment by wenzeslaus** [comment] 2024-02-13 15:13
Thanks for reporting this. Can you please provide the code to reproduce ideally using the NC SPM sample dataset or other public data? The code can be just copied commands from the GUI if you are using it (there is _Copy_ button in the tool dialog).

**Comment by geografin** [comment] 2024-02-14 08:48
`v.dissolve input=over_geo column=subid aggregate_columns=a_length,a_source_elev,a_outlet_elev aggregate_methods=sum,max,min result_columns=LENGTH,SOURCE,OUTLET output=over_geo_diss --overwrite`
This is the command that ends with error. The map taken is a simple rivers layers generated with r.stream.order and overlayed with subwatersheds vector with `v.overlay`.

**Comment by geografin** [comment] 2024-02-14 08:52
I don't use GUI. I use bash linux with GRASS docker image (from main branch, the last one)

**Comment by wenzeslaus** [comment] 2024-02-15 04:04
Sorry @geografin what I meant was a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). @ecodiv was not able to reproduce it, so I'm looking for a way to get the same data and situation you have. Bash is definitively better starting point than GUI, so that's great. Can you try to run relevant commands with the [NC SPM sample dataset](https://grass.osgeo.org/download/data/) and share these commands?

**Comment by geografin** [comment] 2024-02-15 10:41
Well. So take NorthCarolina dataset (full) and reproduce (I copy some maps form the dataset, that are identical to mine by type):
```bash
g.copy vect=roadsmajor,streams_init --overwrite
g.copy vect=zipcodes_wake,geodata_subbasins --overwrite
v.overlay ainput=streams_init binput=geodata_subbasins operator=and atype=line output=over_geo --overwrite
v.db.addcolumn map=over_geo columns="subid VARCHAR(15),maindown VARCHAR(15)"
v.db.update map=over_geo column=subid query_column="CAST(ZIPCODE_ID AS varchar)" where="ZIPCODE_ID <> 'N/A'"
```
last command result in error and I even can't go further
```ERROR: Error while executing: 'UPDATE over_geo SET subid=CAST(ZIPCODE_ID AS
       varchar) WHERE ZIPCODE_ID <> 'N/A''
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.0\apps\grass\grass78\scripts\v.db.update.py", line 129, in <module>
    sys.exit(main())
  File "C:\PROGRA~1\QGIS32~1.0\apps\grass\grass78\scripts\v.db.update.py", line 120, in main
    grass.write_command('db.execute', input='-', database=database, driver=driver, stdin=cmd)
  File "C:\PROGRA~1\QGIS32~1.0\apps\grass\grass78\etc\python\grass\script\core.py", line 588, in write_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "C:\PROGRA~1\QGIS32~1.0\apps\grass\grass78\etc\python\grass\script\core.py", line 342, in handle_errors
    raise CalledModuleError(module=None, code=code,
grass.exceptions.CalledModuleError: Module run None db.execute input=- database=C:\Users\jasinskiy.MMDOM\Downloads\nc_spm_08_grass7\PERMANENT\sqlite\sqlite.db driver=sqlite ended with error
Process ended with non-zero return code 1. See errors in the (error) output.```

**Comment by geografin** [comment] 2024-02-15 10:45
If there was no error I would go further with a command:
```v.dissolve input=over_geo column=subid aggregate_columns=SHAPE_LEN aggregate_methods=sum result_columns=LENGTH output=over_geo_diss --overwrite```
that results in an error in my case and which is all this question about

**Comment by ecodiv** [comment] 2024-02-16 14:48
@geografin I can confirm the example results in the reported error.  The difference with what I tried is that here you want to dissolve line features, right?

@wenzeslaus The manual exclusively refers to polygon data. Is this function supposed to be able to dissolve line features?

**Comment by wenzeslaus** [comment] 2024-02-16 15:48
> ...Is this function supposed to be able to dissolve line features?

Thanks for looking into this. I didn't dive into that and focused on the attribute aggregation, so I don't know from top of my head. The geometrical part is taken care of by v.reclass and v.extract, so you can check those. The lines in [v.dissolve](https://github.com/OSGeo/grass/blob/main/scripts/v.dissolve/v.dissolve.py#L631C13-L645C14) are:

```python
            gs.run_command(
                "v.reclass",
                input=input_vector,
                output=tmpfile,
                layer=layer,
                column=column,
            )
            gs.run_command(
                "v.extract",
                flags="d",
                input=tmpfile,
                output=output,
                type="area",
                layer=layer,
            )
```

**Comment by ecodiv** [comment] 2024-02-16 19:51
> > ...Is this function supposed to be able to dissolve line features?
> 
> Thanks for looking into this. I didn't dive into that and focused on the attribute aggregation, so I don't know from top of my head. The geometrical part is taken care of by v.reclass and v.extract, so you can check those. The lines in [v.dissolve](https://github.com/OSGeo/grass/blob/main/scripts/v.dissolve/v.dissolve.py#L631C13-L645C14) are:
> 
> ```python
>             gs.run_command(
>                 "v.reclass",
>                 input=input_vector,
>                 output=tmpfile,
>                 layer=layer,
>                 column=column,
>             )
>             gs.run_command(
>                 "v.extract",
>                 flags="d",
>                 input=tmpfile,
>                 output=output,
>                 type="area",
>                 layer=layer,
>             )
> ```

Without having tested it, the type="area" might be the problem?

**Comment by wenzeslaus** [comment] 2024-02-16 20:48
> Without having tested it, the type="area" might be the problem?

Haha, that sure looks like that! Maybe deleting it will do trick?

**Comment by geografin** [comment] 2024-02-19 06:31
> The difference with what I tried is that here you want to dissolve line features, right?
@ecodiv yes, right! And v.extract doesn't support aggregation by specific columns. So my task can't be done with GRASS.

**Comment by ecodiv** [comment] 2024-02-19 07:41
> > The difference with what I tried is that here you want to dissolve line features, right?
> > @ecodiv yes, right! And v.extract doesn't support aggregation by specific columns. So my task can't be done with GRASS.

I think it can be used, see #3433

**Comment by wenzeslaus** [comment] 2024-02-23 01:58
#3433 will be merged in following hours when the CI is done testing it. Thanks @ecodiv for the update!

**Closed** 2024-02-23 03:14 UTC
Labels: bug, vector
