### ISSUE TITLE
PRI_OFF_T hack can not be used in translatable strings

### ISSUE THREAD

**Issue by slichtzzz** [OSGeo/grass#2805] opened 2023-02-06 13:15 UTC
The end of this line is not added to translation file.
In the end, the po-file contains only the larger chunk of this line:

"Coor file of vector map <%s@%s> is larger than it should be (%"

https://github.com/OSGeo/grass/blob/ce08116b890253ee5fc79ba6fda1e43bd8ee3355/locale/templates/grasslibs.pot#L5631

So, the end of this line ("%" PRI_OFF_T " bytes excess") will not be translated. Looks like this happens due to quotes around PRI_OFF_T.

https://github.com/OSGeo/grass/blob/ce08116b890253ee5fc79ba6fda1e43bd8ee3355/lib/vector/Vlib/open_nat.c#L154

**Comment by marisn** [comment] 2023-02-07 06:48
Duplicate of #2806 Will be fixed by merging #2807

**Closed by marisn** 2023-02-07 06:48 UTC
Labels: C, translation
