### ISSUE TITLE
[Bug] recv_some fails in macOS CI with unexpected end of data

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass#2825] opened 2023-02-13 18:37 UTC
**Describe the bug**

Test of `recv_some` from `gui/wxpython/core/gcmd.py` fails with `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4: unexpected end of data`.

**To Reproduce**

Perhaps run tests locally.

**Screenshots**

```
Running ./gui/wxpython/core/testsuite/test_gcmd.py...
========================================================================
E
======================================================================
ERROR: test_decode (__main__.Recv_SomeTest.test_decode)
Multibyte chars should not be split
----------------------------------------------------------------------
Traceback (most recent call last):
  File "gui/wxpython/core/testsuite/test_gcmd.py", line 27, in test_decode
    recv_some(p, e=0)
  File "gui/wxpython/core/gcmd.py", line 325, in recv_some
    y.append(decode(r))
             ^^^^^^^^^
  File "etc/python/grass/script/utils.py", line 201, in decode
    return bytes_.decode(enc)
           ^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 4: unexpected end of data

----------------------------------------------------------------------
Ran 1 test in 0.002s
FAILED (errors=1)
========================================================================
FAILED ./gui/wxpython/core/testsuite/test_gcmd.py (1 test failed)
```

**System description**

- Operating system: macOS
- GRASS GIS version: main branch

**Additional context**

Couple last commits on main and PRs are failing macOS CI with this error. Threads are involved, so perhaps there is some randomness to it.

This seems to be the same as #2720 but here a test fails and it seems to be happening on macOS as opposed to with long outputs.

**Comment by marisn** [comment] 2023-02-14 06:31
This is a duplicate of #2720. The test case clearly labels the test being made for #2720.

**Closed by marisn** 2023-02-14 06:31 UTC
Labels: bug
