### ISSUE TITLE
Enabling GitHub Discussions

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass#1826] opened 2021-08-26 19:14 UTC
Dear GRASSers,
please consider enabling GitHub Discussions. It will be a great 'resource' in improving GRASS GIS and serving the community that uses and supports GRASS GIS.

**Comment by NikosAlexandris** [comment] 2021-08-28 05:52
Hallo Stefan!

In the background of every discussion for a change, for something new, there is always -- and naturally so -- the question _who is going to do it?_. Well, one answer is _everyone_ and _altogether_ could/should. Step by step, the same way GRASS GIS made it till today. This means for all to embrace and dive-in. If it's not going to work, it's not and that is ok.

For the matter: do you find it easier to search in the e-mail archives to find an answer for a question around programming or else software use or science or anything similar than going through StackExchange? Isn't gitter offering an easy way to chat about development issues (both synchronous and asynchronous)? Do you use gitter's rooms to discuss stuff (both in public and in private) about https://gitter.im/matplotlib/matplotlib for example? What is there to maintain? Isn't it practically zero maintenance? Isn't this the purpose of the Q&A platforms, To take off the load of maintaining yet another big thing?

>ps- If I will be given access, I will maintain Discussions.  I can do this because I think there is nothing practically to maintain. I can setup a gitter channel or channels, link to repositories and let commit messages to arrive there-in, all in little time. There is not much to maintain.

**Comment by NikosAlexandris** [comment] 2021-08-28 06:12
@OSGeo/grass-admins @OSGeo/grass-committers, I request access to:
-  [enable GitHub Discussions](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository)
- spend some time during the week to [organize discussions](https://docs.github.com/en/discussions/quickstart#organizing-discussions)
- and to moderate (see [Promoting healthy conversations](https://docs.github.com/en/discussions/quickstart#promoting-healthy-conversations))

on my own or along with other contributors.

> Please refer to the [PSC/Election2016](https://trac.osgeo.org/grass/wiki/PSC/Election2016) page's [history](https://trac.osgeo.org/grass/wiki/PSC/Election2016?action=history) which is relevant for the evaluation of my commitment and voluntary contribution to the project's organisational/administrative tasks.

**Comment by mlennert** [comment] 2021-09-01 09:51
@NikosAlexandris You seem to display the discussion that happened on the mailing list as some debate between modern and old technologies. If you read the posts carefully, that is not really true.

The biggest issue raised by most is that of dispersion of discussions. We already have this happening now where a lot of fundamental discussions are happening in PRs and (at least that is the feeling I get) less people are involved in these discussions compared to when everything went through the mailing list. So, the point here is not about old tech nostalgia, but about how to ensure coherence within the group of developers, something that I've seen as one of the big strengths of GRASS GIS development. I do concede,  however, that this aim for coherence might be unrealistic if we have increasing numbers of contributors and especially since ways of contributing have fundamentally changed though the move to github and PRs. Personally, I don't have a religion concerning the tools, I just don't want to have to use 5 tools in parallel to make sure I'm informed about important issues discussed concerning GRASS GIS.

And for me (being old-school) email is still the best way of concentrating different information flows into one channel. We use Slack intensively at work, for example, but I do see the issue of high numbers of channels and the difficulty of following all important discussions. But I imagine there are ways to solve this issue with other tools than email, and I would just need guidance. Github does allow to respond to email notifications by email and so I imagine that this is also possible for github discussions, which would probably solve this issue for us (I still have difficulties finding the right filter settings to really see only important email notifications, and not every single interaction - but again that's me needing guidance, probably not linked to the tools).

If we agree that dispersal is an issue, but that mailing lists are not the way to go anymore as the central place of discussion, then let's discuss all available tools and chose among them, also taking into account issues such as dependency of a proprietary provider, etc. But please let's not just open new channels everywhere just because it's the cool thing to do ;-).

**Comment by mlennert** [comment] 2021-09-01 09:53
See https://github.com/github/feedback/discussions/59 for a discussion on the difficulties of filtering github email notifications.

**Comment by NikosAlexandris** [comment] 2021-09-01 10:43
Hi @mlennert, I read carefully what you wrote/write.

> @NikosAlexandris You seem to display the discussion that happened on the mailing list as some debate between modern and old technologies. If you read the posts carefully, that is not really true.

I don't display any debate between old and new. If this is your interpretation, I respect it. But I don't accept it. I have a genuine interest in all about GRASS GIS and I do as possible (mostly behind the scenes) to contribute the way I think is best and can. It's all honest questions I share openly.

> The biggest issue raised by most is that of dispersion of discussions. We already have this happening now where a lot of fundamental discussions are happening in PRs and (at least that is the feeling I get) less people are involved in these discussions compared to when everything went through the mailing list. So, the point here is not about old tech nostalgia, but about how to ensure coherence within the group of developers, something that I've seen as one of the big strengths of GRASS GIS development. I do concede, however, that this aim for coherence might be unrealistic if we have increasing numbers of contributors and especially since ways of contributing have fundamentally changed though the move to github and PRs. Personally, I don't have a religion concerning the tools, I just don't want to have to use 5 tools in parallel to make sure I'm informed about important issues discussed concerning GRASS GIS.

I am not a core-developer so I have no right to participate in a discussion on the core dev-team coordinates internally. So, I have nothing to say about the dev-team. I do have a direct interest to participate in the project as an Addons contributor, as a long-year GRASS GIS user and OSGeo member. Discussions is the 'natural' place to discuss thigs about GRASS GIS from my perspective, indeed because of its natural integration with the repository.

I agree that fragmentation is not good overall -- except for when it's stimulating and leads to new forms. I would question 'why not keep dev-work related communication wherever the dev-team sees best fit?' andd still acticate Discussions for new users, for users like me and everything about GRASS-GIS except for what the dev-team is discussing? Sure, it's not that simple.-

> And for me (being old-school) email is still the best way of concentrating different information flows into one channel. We use Slack intensively at work, for example, but I do see the issue of high numbers of channels and the difficulty of following all important discussions. But I imagine there are ways to solve this issue with other tools than email, and I would just need guidance. Github does allow to respond to email notifications by email and so I imagine that this is also possible for github discussions, which would probably solve this issue for us (I still have difficulties finding the right filter settings to really see only important email notifications, and not every single interaction - but again that's me needing guidance, probably not linked to the tools).

There is a natural 'old-school' vs. 'new-school' clustering, which you identify here in the beginning of your sentence. I want to nore that I am also for e-mail to communicate! But one can simply not beat the efficacy of modern tools in searching for answers.

> If we agree that dispersal is an issue, but that mailing lists are not the way to go anymore as the central place of discussion, then let's discuss all available tools and chose among them, also taking into account issues such as dependency of a proprietary provider, etc. But please let's not just open new channels everywhere just because it's the cool thing to do ;-).

In overview,
- I have well thought my request for enabling Discussions -- it's something I think will help, something I can contribute to, something that will save time in interacting as a user with other users and developers
- I am not participating in the coordination of the dev-team and I am not indirectly willing to influence anything
- I am not in favor to start using new tools simply because they are cool
- proprietary vs. open source:  hmmm.... lots of open questions here (own git server maintenance?, OSGeo in GitHub, why not GitLab, why not elsewhere, etc.) but at the very minimum, the project should ensure it can pack it's stuff and move elsewhere If it will be ever necessary (for example if Microsoft decides to charge each commit or similar!)

Cheers :-)

**Comment by wenzeslaus** [comment] 2021-09-01 14:25
The discussion on grass-dev mentioned things like migrating our mailing list to mailman3, integrating with hyper kitty, promoting nabble on our GitHub repository and checking whether it would be feasible to sign up to nabble or mailing list with OAuth or GitHub. There was no report or activity regarding those. In the mean time, nabble is going down.

There was also a talk about encouraging all contributors to discuss/mention more significant changes on the mailing list. It seems this happening even without the encouragement. However, the response rate seems to be relatively low and some developers conclude that they "got only a bit of feedback" on mailing list.

Things like vendor lock-in and fragmentation are valid concerns. Vendor lock-in applies only partially here, we don't shut down the mailing list to avoid being trapped and nor we are replacing grass-dev mailing list as a place to officially reach all the core and highly involved developers and concerned users. This is similar to how we are mitigating vendor lock-in of having PRs on GitHub, besides having the benefits of Git, we capture the important pieces of discussion or decisions in the commit message (right everyone? :smile: ).

As for the fragmentation, I think the main purpose of GitHub Discussions is to reach people on GitHub who are maybe using 10 other projects on GitHub and need to ask this one question about GRASS GIS. Additionally, nothing goes to the source code unless there is a PR, so there is a one and only channel for that. Finally, we don't limit people in having private conversations about GRASS GIS nor we control what happens during community sprints, so there was always a need for self-discipline to share what is needed through the right channels at the right time. As far as seeing and participating in communication on GitHub, from the 10 people involved in the grass-dev discussion about GitHub Discussions which lasted for almost a month, 3 of us are already here after 6 days, so people do see it.

Given commitment by @NikosAlexandris to "spend some time during the week to organize discussions and to moderate" them, the lack of action in other areas since the last time this was brought up, and seconding from @petrasovaa (+1) and no objections from @ninsbl, I'm going to enable GitHub Discussions. Let's try it, see how it goes. We can evaluate it in a year.

**Comment by cmbarton** [comment] 2021-09-02 21:51
I've had similar conversations in the CoMSES.Net community. How to facilitate communication while letting people 'tune out' non-relevant communication to as to not be overwhelmed. There is not an easy answer so far, and the increasing diversity of potential communication channels has not made this easier, but rather more complicated with greater potential for fragmentation and dilution of important information exchange. 

I agree with Vaclav and Nikos that GitHub discussions is worth a try. BUT, here are some things to consider.

1. Is enabling GitHub discussions being done with the idea of possibly replacing email lists or for adding another communication channel? 
  - This is part of the discussion so far. If it is the former, we might want to encourage migration by mirroring the structure of the current set of email lists in GitHub discussions--especially the user and dev list. Or perhaps just start with one list and see if people are encouraged to migrate. I don't yet know enough about GitHub discussions to know if we can have separate channels like our current mailing lists or not. But it is worth looking into.
  - Migrating to GitHub discussions might actually make my email overflow worse. This is something we need to consider if our goal is to have more efficient communication with less noise. The reason it could be worse is because of the way GitHub notifications are set up currently. As a member of the dev team, I'd like to hear about and follow issues that I find relevant, that I'm mentioned on, or where I've contributed to discussions (like here). But even though I've got 'participating and @mentions only' checked, I seem to get notifications in my email for every issue that comes up. In email, at least I can have it delivered as a digest. The 'custom' option is only if you want to *add* additional notification for different classes of communication (issues, PR, etc). Filtering this to the most relevant communication does not seem possible. But maybe there is a way to configure this.
  - Discussions seems like a good way to archive communication and be able to search it. The grass lists are very active. After a few years, how will this scale? The current email archive is very large. Maybe this is no problem in GitHub, but worth checking to see if it will scale OK. 
  - One potential advantage is to more easily and directly link discussion to issues and PRs. If we could follow a standard best practice, this could be a real benefit: 1) start with a discussion, 2) if there is an action item proposed, it moves to an issue linked with the discussion, 3) if the issue is acted on by a PR, it is likewise cross-linked to the issue and discussion thread. 

2. If GitHub discussions are not envisioned as ultimately replacing the mailing lists, I am worried about fragmentation like Morritz. We would need to have a well defined GitHub communication channel so that users would know where to post and search (email or GitHub). 

3. If we want to be even more adventurous, n alternative communication channel to email or GitHub discussions that shows promise is [Discord](https://discord.com). I'm trying it for an international consortium initiative and it seems to work well. It can have multiple channels and channel groups, threaded discussions, and the potential of live audio/video rooms for live interaction. It also has the potential to link with GitHub and other media channels. Perhaps worth considering at some point.

**Comment by NikosAlexandris** [comment] 2021-09-03 07:37
> > ps- If I will be given access, I will maintain Discussions.  I can do this because I think there is nothing practically to maintain. I can setup a gitter channel or channels, link to repositories and let commit messages to arrive there-in, all in little time. There is not much to maintain.

By the way, moderation != maintenance.

**Comment by NikosAlexandris** [comment] 2021-09-03 16:27
> .. 
>     2. If we want to be even more adventurous, an alternative communication channel to email or GitHub discussions that shows promise is [Discord](https://discord.com). I'm trying it for an international consortium initiative and it seems to work well. It can have multiple channels and channel groups, threaded discussions, and the potential of live audio/video rooms for live interaction. It also has the potential to link with GitHub and other media channels. Perhaps worth considering at some point.

Awesome Michael! Discord will be great!

**Comment by NikosAlexandris** [comment] 2021-09-03 16:31
> See [github/feedback#59](https://github.com/github/feedback/discussions/59) for a discussion on the difficulties of filtering github email notifications.

I have read it. Given the growing user-base of Discussions in GitHub's world, this should be rather _fixed_ sooner or later and become easy to filter notifications. It would eventually become almost seamless to (old-school) e-mail users to interact with members using Discussions.

**Comment by wenzeslaus** [comment] 2021-09-12 18:34
Discussions are enabled and tested. Closing the issue.

**Closed by wenzeslaus** 2021-09-12 18:34 UTC
Labels: enhancement
