### ISSUE TITLE
[Bug] columns filter for t.rast.list  fails with method=gran

### ISSUE THREAD

**Issue by chaedri** [OSGeo/grass#2205] opened 2022-02-13 18:40 UTC
**Describe the bug**
When using `t.rast.list` with the `method=gran` option, the `columns` filter does not work. Instead of filtering the table to just the columns selected, it returns the whole table, unfiltered.

**To Reproduce**

1. Use sample temporal dataset from: [http://ncsu-geoforall-lab.github.io/grass-temporal-workshop/](http://ncsu-geoforall-lab.github.io/grass-temporal-workshop/)
2. Run `t.create output=NagsHead_99_08 type=strds temporaltype=relative title="Nags Head elevation series" description="from 1999 to 2008 with gaps"`
3. Register rasters NH_1999_1m, NH_2001_1m, NH_2004_1m, NH_2005_1m, NH_2007_1m and NH_2008_1m to NagsHead_99_08, the new space time dataset, with unit of years.
4. Run `t.rast.list input=NagsHead_99_08 columns=name` to see expected behavior of `columns` filter
5.  See expected output:
```
name
NH_1999_1m
NH_2001_1m
NH_2004_1m
NH_2005_1m
NH_2007_1m
NH_2008_1m
```
6. Run same as above but with `method=gran` to see unexpected behavior (`t.rast.list input=NagsHead_99_08 method=gran columns=name`):
```
id|name|mapset|start_time|end_time|interval_length|distance_from_begin
NH_1999_1m@NagsHead_series|NH_1999_1m|NagsHead_series|1999|2000|1|0
None|None|None|2000|2001|1|1
NH_2001_1m@NagsHead_series|NH_2001_1m|NagsHead_series|2001|2002|1|2
None|None|None|2002|2003|1|3
None|None|None|2003|2004|1|4
NH_2004_1m@NagsHead_series|NH_2004_1m|NagsHead_series|2004|2005|1|5
NH_2005_1m@NagsHead_series|NH_2005_1m|NagsHead_series|2005|2006|1|6
None|None|None|2006|2007|1|7
NH_2007_1m@NagsHead_series|NH_2007_1m|NagsHead_series|2007|2008|1|8
NH_2008_1m@NagsHead_series|NH_2008_1m|NagsHead_series|2008|2009|1|9
```

**Expected behavior**
Expected t.rast.list to return only `name` column.

**System description (please complete the following information):**

- Operating System: Windows and Linux; haven't tested on Mac
- GRASS GIS version: 8.0 and 7.8

**Comment by veroandreo** [comment] 2022-02-14 22:42
I confirm this. However, it does work as you would expect if you remove `method=gran`. Do you need this method of printing for some special reason? I'm thinking this is probably the expected behavior if you use granularity as method, since it prints interval length and distance from beginning of the time series for each map.

**Comment by petrasovaa** [comment] 2022-02-15 14:53
> I confirm this. However, it does work as you would expect if you remove `method=gran`. Do you need this method of printing for some special reason? I'm thinking this is probably the expected behavior if you use granularity as method, since it prints interval length and distance from beginning of the time series for each map.

I agree that was the intention and it seems it's also documented in the manual:

    Method col is the default option and sensitive to the column,order and where options.

On the other hand, it is not expected behavior and I don't see a big reason for this behavior. Seems columns should be customizable in any case, potentially with different defaults.

**Comment by neteler** [comment] 2022-12-14 20:18
(see also issue #2688)

**Comment by veroandreo** [comment] 2022-12-26 16:04
Coming back here... seems to work as expected in 8.2... Was there any change fixing this?

My tests: 

```t.rast.list LST_Day_monthly columns=name
name
MOD11B3.A2015001.h11v05.single_LST_Day_6km
MOD11B3.A2015032.h11v05.single_LST_Day_6km
MOD11B3.A2015060.h11v05.single_LST_Day_6km
MOD11B3.A2015091.h11v05.single_LST_Day_6km
MOD11B3.A2015121.h11v05.single_LST_Day_6km
MOD11B3.A2015152.h11v05.single_LST_Day_6km
MOD11B3.A2015182.h11v05.single_LST_Day_6km
MOD11B3.A2015213.h11v05.single_LST_Day_6km
MOD11B3.A2015244.h11v05.single_LST_Day_6km
MOD11B3.A2015274.h11v05.single_LST_Day_6km
MOD11B3.A2015305.h11v05.single_LST_Day_6km
MOD11B3.A2015335.h11v05.single_LST_Day_6km
MOD11B3.A2016001.h11v05.single_LST_Day_6km
MOD11B3.A2016032.h11v05.single_LST_Day_6km
MOD11B3.A2016061.h11v05.single_LST_Day_6km

GRASS nc_spm_08_grass7/modis_lst:~ > t.rast.list LST_Day_monthly method=gran
id|name|mapset|start_time|end_time|interval_length|distance_from_begin
MOD11B3.A2015001.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015001.h11v05.single_LST_Day_6km|modis_lst|2015-01-01 00:00:00|2015-02-01 00:00:00|31.0|0.0
MOD11B3.A2015032.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015032.h11v05.single_LST_Day_6km|modis_lst|2015-02-01 00:00:00|2015-03-01 00:00:00|28.0|31.0
MOD11B3.A2015060.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015060.h11v05.single_LST_Day_6km|modis_lst|2015-03-01 00:00:00|2015-04-01 00:00:00|31.0|59.0
MOD11B3.A2015091.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015091.h11v05.single_LST_Day_6km|modis_lst|2015-04-01 00:00:00|2015-05-01 00:00:00|30.0|90.0
MOD11B3.A2015121.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015121.h11v05.single_LST_Day_6km|modis_lst|2015-05-01 00:00:00|2015-06-01 00:00:00|31.0|120.0
MOD11B3.A2015152.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015152.h11v05.single_LST_Day_6km|modis_lst|2015-06-01 00:00:00|2015-07-01 00:00:00|30.0|151.0
MOD11B3.A2015182.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015182.h11v05.single_LST_Day_6km|modis_lst|2015-07-01 00:00:00|2015-08-01 00:00:00|31.0|181.0
MOD11B3.A2015213.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015213.h11v05.single_LST_Day_6km|modis_lst|2015-08-01 00:00:00|2015-09-01 00:00:00|31.0|212.0
MOD11B3.A2015244.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015244.h11v05.single_LST_Day_6km|modis_lst|2015-09-01 00:00:00|2015-10-01 00:00:00|30.0|243.0
MOD11B3.A2015274.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015274.h11v05.single_LST_Day_6km|modis_lst|2015-10-01 00:00:00|2015-11-01 00:00:00|31.0|273.0
MOD11B3.A2015305.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015305.h11v05.single_LST_Day_6km|modis_lst|2015-11-01 00:00:00|2015-12-01 00:00:00|30.0|304.0
MOD11B3.A2015335.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2015335.h11v05.single_LST_Day_6km|modis_lst|2015-12-01 00:00:00|2016-01-01 00:00:00|31.0|334.0
MOD11B3.A2016001.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2016001.h11v05.single_LST_Day_6km|modis_lst|2016-01-01 00:00:00|2016-02-01 00:00:00|31.0|365.0
MOD11B3.A2016032.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2016032.h11v05.single_LST_Day_6km|modis_lst|2016-02-01 00:00:00|2016-03-01 00:00:00|29.0|396.0
MOD11B3.A2016061.h11v05.single_LST_Day_6km@modis_lst|MOD11B3.A2016061.h11v05.single_LST_Day_6km|modis_lst|2016-03-01 00:00:00|2016-04-01 00:00:00|31.0|425.0

GRASS nc_spm_08_grass7/modis_lst:~ > t.rast.list LST_Day_monthly method=gran columns=name
name
MOD11B3.A2015001.h11v05.single_LST_Day_6km
MOD11B3.A2015032.h11v05.single_LST_Day_6km
MOD11B3.A2015060.h11v05.single_LST_Day_6km
MOD11B3.A2015091.h11v05.single_LST_Day_6km
MOD11B3.A2015121.h11v05.single_LST_Day_6km
MOD11B3.A2015152.h11v05.single_LST_Day_6km
MOD11B3.A2015182.h11v05.single_LST_Day_6km
MOD11B3.A2015213.h11v05.single_LST_Day_6km
MOD11B3.A2015244.h11v05.single_LST_Day_6km
MOD11B3.A2015274.h11v05.single_LST_Day_6km
MOD11B3.A2015305.h11v05.single_LST_Day_6km
MOD11B3.A2015335.h11v05.single_LST_Day_6km
MOD11B3.A2016001.h11v05.single_LST_Day_6km
MOD11B3.A2016032.h11v05.single_LST_Day_6km
MOD11B3.A2016061.h11v05.single_LST_Day_6km

GRASS nc_spm_08_grass7/modis_lst:~ > t.unregister LST_Day_monthly type=raster maps=MOD11B3.A2016001.h11v05.single_LST_Day_6km
Unregister maps
 100%
Unregister maps from space time dataset <LST_Day_monthly>

GRASS nc_spm_08_grass7/modis_lst:~ > t.rast.list LST_Day_monthly columns=name
name
MOD11B3.A2015001.h11v05.single_LST_Day_6km
MOD11B3.A2015032.h11v05.single_LST_Day_6km
MOD11B3.A2015060.h11v05.single_LST_Day_6km
MOD11B3.A2015091.h11v05.single_LST_Day_6km
MOD11B3.A2015121.h11v05.single_LST_Day_6km
MOD11B3.A2015152.h11v05.single_LST_Day_6km
MOD11B3.A2015182.h11v05.single_LST_Day_6km
MOD11B3.A2015213.h11v05.single_LST_Day_6km
MOD11B3.A2015244.h11v05.single_LST_Day_6km
MOD11B3.A2015274.h11v05.single_LST_Day_6km
MOD11B3.A2015305.h11v05.single_LST_Day_6km
MOD11B3.A2015335.h11v05.single_LST_Day_6km
MOD11B3.A2016032.h11v05.single_LST_Day_6km
MOD11B3.A2016061.h11v05.single_LST_Day_6km

GRASS nc_spm_08_grass7/modis_lst:~ > t.rast.list LST_Day_monthly method=gran columns=name
name
MOD11B3.A2015001.h11v05.single_LST_Day_6km
MOD11B3.A2015032.h11v05.single_LST_Day_6km
MOD11B3.A2015060.h11v05.single_LST_Day_6km
MOD11B3.A2015091.h11v05.single_LST_Day_6km
MOD11B3.A2015121.h11v05.single_LST_Day_6km
MOD11B3.A2015152.h11v05.single_LST_Day_6km
MOD11B3.A2015182.h11v05.single_LST_Day_6km
MOD11B3.A2015213.h11v05.single_LST_Day_6km
MOD11B3.A2015244.h11v05.single_LST_Day_6km
MOD11B3.A2015274.h11v05.single_LST_Day_6km
MOD11B3.A2015305.h11v05.single_LST_Day_6km
MOD11B3.A2015335.h11v05.single_LST_Day_6km
None
MOD11B3.A2016032.h11v05.single_LST_Day_6km
MOD11B3.A2016061.h11v05.single_LST_Day_6km
```

I tried with unregistering a map in case the problem could be related to missing timestamps... but, it seems to work ok, am I right?

**Comment by ninsbl** [comment] 2024-05-24 22:13
I can confirm that columns can be selected in 8.4. So, I would suggest to close this issue...

**Comment by echoix** [comment] 2024-05-25 02:32
It's always a bit worrisome to have a bug that is magically fixed. That means that we don't know where it was from. But seeing the age of the issue, and the amount of work done on so much parts of the code, it might be the right thing to close as it isn't an issue anymore. Wasn't found in December 2022. (Grass 8.2), and isn't an issue in May 2024 (almost grass 8.4). 


If needed, we can reopen this issue, or have a new one.

**Closed** 2024-05-25 02:33 UTC
Labels: bug, temporal

**Comment by wenzeslaus** [comment] 2024-05-26 01:22
The report says 8.0. I made a big rewrite for 8.2 in #2258. The description says: 

> Columns can be now specified for any option (previously only for cols/list and partially for comma/line output).

And also:

> Most code is shared between the two main branches of code (simple list versus delta/gran methods code).

I would say, I fixed this. :smile:
