### ISSUE TITLE
[Bug] g.gui.vdigit: "Quit digitizing tool" command leaves blank mapdisplay

### ISSUE THREAD

**Issue by nilason** [OSGeo/grass#530] opened 2020-04-19 19:34 UTC
**Describe the bug**
Exiting a vector digitizing session clicking on the "Quit digitizer"-button, clears the mapdisplay, redraws, but does **not** redraw the just closed layer.

**To Reproduce**

1. Select and start editing mode for a vector layer
2. Click on ''Quit digitizing" button
3. Mapdiplay is cleared and redrawed (but not the layer that was just closed).
4. Clicking "Render map" button, redraws the map (including the layer that was closed).

**Expected behavior**
Quitting the digitizing should trigger the mapdisplay to be redrawn with all layers automatically.

**System description:**

- Operating System: tested on macOS

```
> g.version -rge
version=7.9.dev
date=2020
revision=4e05bc7de
build_date=2020-04-17
build_platform=x86_64-apple-darwin18.7.0
build_off_t_size=8
libgis_revision=f062bffc8
libgis_date="Tue Mar 31 20:34:57 2020 +0200"
proj=6.3.1
gdal=3.0.3
geos=3.8.1
sqlite=3.31.1

Python=3.7.7
wx.version()='4.0.7.post2 osx-cocoa (phoenix) wxWidgets 3.0.5'
```

**Additional context**
This issue was introduced with https://github.com/OSGeo/grass/commit/bcab74081cbf53d2ee774c720eb3cc44c9edcb6b.

**Comment by nilason** [comment] 2020-04-21 21:36
Is this a mac specific issue or can it be reproduced on other platforms as well?
This info could be useful for fixing this.

**Comment by petrasovaa** [comment] 2020-04-23 02:11
I can't reproduce it (Ubuntu 18.04, the same wx version), I tried selecting the vector from the combobox and clicking edit tool in layer manager, but I haven't seen any problem. I don't immediately see how that commit could affect this but everything is possible...

**Comment by nilason** [comment] 2020-04-23 10:46
> I can't reproduce it (Ubuntu 18.04, the same wx version), I tried selecting the vector from the combobox and clicking edit tool in layer manager, but I haven't seen any problem. I don't immediately see how that commit could affect this but everything is possible...

Thanks for testing! 
I have this issue regardless how/where I start editing. I’ll look into this.

**Comment by hellik** [comment] 2020-04-23 19:55
It's also in grass in Windows

**Comment by nilason** [comment] 2020-04-23 20:11
> It's also in grass in Windows

I didn’t see that one coming, thanks for the info!

**Comment by petrasovaa** [comment] 2020-04-24 02:16
That's weird, could someone else try with GTK on Linux? Maybe I missed it somehow.

**Comment by tmszi** [comment] 2020-04-24 07:30
I can't reproduce it on GNU/Linux OS.

Gentoo distribution:

```
> g.version -rge
version=7.9.dev
date=2020
revision=1fbfd5f6b
build_date=2020-04-23
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=4e5d2f0c9
libgis_date="Mon Apr 20 13:29:17 2020 +0200"
proj=5.2.0
gdal=2.4.3
geos=3.8.0
sqlite=3.31.1

wx.version()
4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.4
```
Ubuntu distribution (19.10):

```
> g.version -rge
version=7.9.dev
date=2020
revision=f59a1c088
build_date=2020-04-21
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=4e5d2f0c9
libgis_date="Mon Apr 20 13:29:17 2020 +0200"
proj=5.2.0
gdal=2.4.0
geos=3.7.1
sqlite=3.27.2

wx.version()
4.0.6 gtk3 (phoenix) wxWidgets 3.0.4
```

I can reproduce it on MS Windows 10 OS:

```
> g.version -rge
version=7.9.dev
date=2020
revision=39415e87b
build_date=2020-04-22
build_platform=x86_64-w64-mingw32
build_off_t_size=8
libgis_revision=4e5d2f0c9
libgis_date="Mon Apr 20 13:29:17 2020 +0200"
proj=6.3.1
gdal=3.0.4
geos=3.8.1
sqlite=3.29.0

wx.version()
4.0.7 msw (phoenix) wxWidgets 3.0.5
```
Could you (@nilason, @hellik) confirm this error message please? (switch to Console page (tab) on Layer Manager)

```
Traceback (most recent call last):
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\gthread.py", line 121, in OnDone

event.ondone(event)
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 469, in OnRenderDone

self.updateProgress.emit(layer=self.layer)
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\signal.py", line 229, in
emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\dispatcher.py", line 349, in
send

**named
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\robustapply.py", line 60, in
robustApply

return receiver(*arguments, **named)
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 743, in
ReportProgress

self.renderDone.emit()
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\signal.py", line 229, in
emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\dispatcher.py", line 349, in
send

**named
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\robustapply.py", line 60, in
robustApply

return receiver(*arguments, **named)
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 679, in OnRenderDone

self.Render()
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 604, in Render

if self._renderLayers(env, force) == 0:
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 543, in _renderLayers

layer.GetRenderMgr().updateProgress.emit(layer=layer)
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\signal.py", line 229, in
emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\dispatcher.py", line 349, in
send

**named
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\robustapply.py", line 60, in
robustApply

return receiver(*arguments, **named)
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 743, in
ReportProgress

self.renderDone.emit()
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\signal.py", line 229, in
emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\dispatcher.py", line 349, in
send

**named
  File "C:\Program Files\GRASS GIS
7.9\etc\python\grass\pydispatch\robustapply.py", line 60, in
robustApply

return receiver(*arguments, **named)
  File "C:\Program Files\GRASS GIS
7.9\gui\wxpython\core\render.py", line 650, in OnRenderDone

raise GException(_("Rendering failed: %s" % msg))
core.gcmd
.
GException
:
Rendering failed: Expecting 807x501 image but got 807x466
image.

```

**Comment by nilason** [comment] 2020-04-24 07:50
> Could you (@nilason, @hellik) confirm this error message please? (switch to Console page (tab) on Layer Manager)

@tmszi Yes, I overlooked the console output, which is:

```
Traceback (most recent call last):
  File "/usr/local/grass79/gui/wxpython/core/gthread.py",
line 121, in OnDone

event.ondone(event)
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 469, in OnRenderDone

self.updateProgress.emit(layer=self.layer)
  File
"/usr/local/grass79/etc/python/grass/pydispatch/signal.py",
line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/usr/local/grass79/etc/python/grass/pydispatch/dispa
tcher.py", line 349, in send

**named
  File "/usr/local/grass79/etc/python/grass/pydispatch/robus
tapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 743, in ReportProgress

self.renderDone.emit()
  File
"/usr/local/grass79/etc/python/grass/pydispatch/signal.py",
line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/usr/local/grass79/etc/python/grass/pydispatch/dispa
tcher.py", line 349, in send

**named
  File "/usr/local/grass79/etc/python/grass/pydispatch/robus
tapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 679, in OnRenderDone

self.Render()
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 604, in Render

if self._renderLayers(env, force) == 0:
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 543, in _renderLayers

layer.GetRenderMgr().updateProgress.emit(layer=layer)
  File
"/usr/local/grass79/etc/python/grass/pydispatch/signal.py",
line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/usr/local/grass79/etc/python/grass/pydispatch/dispa
tcher.py", line 349, in send

**named
  File "/usr/local/grass79/etc/python/grass/pydispatch/robus
tapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 743, in ReportProgress

self.renderDone.emit()
  File
"/usr/local/grass79/etc/python/grass/pydispatch/signal.py",
line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "/usr/local/grass79/etc/python/grass/pydispatch/dispa
tcher.py", line 349, in send

**named
  File "/usr/local/grass79/etc/python/grass/pydispatch/robus
tapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "/usr/local/grass79/gui/wxpython/core/render.py",
line 650, in OnRenderDone

raise GException(_("Rendering failed: %s" % msg))
core.gcmd
.
GException
:
Rendering failed: Expecting 825x622 image but got 825x586
image.
```

**Comment by nilason** [comment] 2020-04-24 07:54
```
Rendering failed: Expecting 825x622 image but got 825x586
image.
```
The difference is probably the toolbar height.

**Comment by hellik** [comment] 2020-04-25 08:48
```

g.gui.vdigit map=myfire@user1                                                   
Bearbeitung der Vektorkarte <myfire@user1> erfolgreich
abgeschlossen
Erstelle Topologie für die Vektorkarte <myfire@user1>...
Registriere Primitive...
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\vdigit\t
oolbars.py", line 1126, in OnShow
    self.UpdateListOfLayers(updateTool=True)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\vdigit\t
oolbars.py", line 1113, in UpdateListOfLayers
    self.combo.SetItems([_('New vector map'), ] +
layerNameList)
  File "C:\OSGEO4~1\apps\Python37\lib\site-
packages\wx\core.py", line 2491, in _ItemContainer_SetItems
    self.Set(items)
RuntimeError: wrapped C/C++ object of type ComboBox has been
deleted
```
with

```
GRASS Version: 7.9.dev                                                          
Code revision: f89b009b5                                                        
Build date: 2020-04-24                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.1                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W)   
```

**Comment by hellik** [comment] 2020-04-25 08:54
```
g.gui.vdigit map=myfire@user1                                                   
Bearbeitung der Vektorkarte <myfire@user1> erfolgreich
abgeschlossen
Erstelle Topologie für die Vektorkarte <myfire@user1>...
Registriere Primitive...
Traceback (most recent call last):
  File
"C:\OSGEO4~1\apps\grass\grass78/scripts/g.gui.vdigit.py",
line 116, in <module>
    main()
  File
"C:\OSGEO4~1\apps\grass\grass78/scripts/g.gui.vdigit.py",
line 113, in main
    app.MainLoop()
  File "C:\OSGEO4~1\apps\Python37\lib\site-
packages\wx\core.py", line 2167, in MainLoop
    rv = wx.PyApp.MainLoop(self)
wx._core.wxAssertionError: C++ assertion "GetEventHandler()
== this" failed at ..\..\src\common\wincmn.cpp(478) in
wxWindowBase::~wxWindowBase(): any pushed event handlers
must have been removed
```
with
                                                 
```
GRASS Version: 7.8.2      
Code revision: 3900fb114                                                        
Build date: 2020-03-06                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.1                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W)
```

**Comment by hellik** [comment] 2020-04-25 09:00
doing digitizing in the map display:

```
Bearbeitung der Vektorkarte <myfire@user1> erfolgreich abgeschlossen            
Erstelle Topologie für die Vektorkarte <myfire@user1>...
Registriere Primitive...
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\gth
read.py", line 121, in OnDone

event.ondone(event)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 469, in OnRenderDone

self.updateProgress.emit(layer=self.layer)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 743, in ReportProgress

self.renderDone.emit()
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 679, in OnRenderDone

self.Render()
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 604, in Render

if self._renderLayers(env, force) == 0:
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 543, in _renderLayers

layer.GetRenderMgr().updateProgress.emit(layer=layer)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 743, in ReportProgress

self.renderDone.emit()
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 650, in OnRenderDone

raise GException(_("Rendering failed: %s" % msg))
core.gcmd
.
GException
:
Rendering failed: Expecting 807x501 image but got 807x466
image.
```
with

```
GRASS Version: 7.9.dev                                                          
Code revision: f89b009b5                                                        
Build date: 2020-04-24                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.1                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W)  
```

but it works with

```
GRASS Version: 7.8.2      
Code revision: 3900fb114                                                        
Build date: 2020-03-06                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.1                                                                     
GEOS: 3.8.0                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W)
```

**Comment by nilason** [comment] 2020-04-25 11:01
> GRASS Version: 7.8.2
> Code` revision: 3900fb114

.. predates:

> Additional context
> This issue was introduced with bcab740.

That’s why it works.

**Comment by petrasovaa** [comment] 2020-04-26 04:16
Could you please test #552?

**Comment by nilason** [comment] 2020-04-26 20:17
Great, #552 solves this for mac. What about for windows, @hellik, @tmszi?

**Comment by tmszi** [comment] 2020-04-28 05:05
I tested it on MS W 10 OS. It works properly without error.

**Comment by hellik** [comment] 2020-04-30 19:49
> 
> 
> Great, #552 solves this for mac. What about for windows, @hellik, @tmszi?

now testing it with

```
GRASS Version: 7.9.dev                                                          
Code revision: e962d5d95                                                        
Build date: 2020-04-29                                                          
Build platform: x86_64-w64-mingw32                                              
GDAL: 3.0.4                                                                     
PROJ: 6.3.1                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.29.0                                                                  
Python: 3.7.0                                                                   
wxPython: 4.0.7                                                                 
Platform: Windows-10-10.0.18362-SP0 (OSGeo4W) 
```
loading a vector into the map display for digitizing, the quit digitizing:

```
Bearbeitung der Vektorkarte <myfire@user1> erfolgreich abgeschlossen            
Erstelle Topologie für die Vektorkarte <myfire@user1>...
Registriere Primitive...
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\gth
read.py", line 121, in OnDone

event.ondone(event)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 469, in OnRenderDone

self.updateProgress.emit(layer=self.layer)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 743, in ReportProgress

self.renderDone.emit()
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 679, in OnRenderDone

self.Render()
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 604, in Render

if self._renderLayers(env, force) == 0:
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 543, in _renderLayers

layer.GetRenderMgr().updateProgress.emit(layer=layer)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 743, in ReportProgress

self.renderDone.emit()
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\signal.py", line 229, in emit

dispatcher.send(signal=self, *args, **kwargs)
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\dispatcher.py", line 349, in send

**named
  File "C:\OSGEO4~1\apps\grass\grass79\etc\python\grass\pydi
spatch\robustapply.py", line 60, in robustApply

return receiver(*arguments, **named)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\core\ren
der.py", line 650, in OnRenderDone

raise GException(_("Rendering failed: %s" % msg))
core.gcmd
.
GException
:
Rendering failed: Expecting 807x501 image but got 807x466
image.
```
now

```
g.gui.vdigit map=myfire@user1                                                   
Bearbeitung der Vektorkarte <myfire@user1> erfolgreich
abgeschlossen
Erstelle Topologie für die Vektorkarte <myfire@user1>...
Registriere Primitive...
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\vdigit\t
oolbars.py", line 1126, in OnShow
    self.UpdateListOfLayers(updateTool=True)
  File "C:\OSGEO4~1\apps\grass\grass79\gui\wxpython\vdigit\t
oolbars.py", line 1113, in UpdateListOfLayers
    self.combo.SetItems([_('New vector map'), ] +
layerNameList)
  File "C:\OSGEO4~1\apps\Python37\lib\site-
packages\wx\core.py", line 2491, in _ItemContainer_SetItems
    self.Set(items)
RuntimeError: wrapped C/C++ object of type ComboBox has been
deleted

```

**Comment by hellik** [comment] 2020-04-30 19:52
> 
> 
> I tested it #552 on MS W 10 OS. It works properly without error.

which version did you tested? OSGeo4W? standalone installer?

could you do?

- g.version -g
- g.version -bre

**Comment by petrasovaa** [comment] 2020-05-01 01:48
Could you try #572?

**Comment by tmszi** [comment] 2020-05-01 05:54
> which version did you tested? OSGeo4W? standalone installer?

These #552, #572 PRs aren't accepted (merged) in the standalone installer release or OSGeo4W yet.

How to apply the #552 PR fix:
1. Make backup:
-  `C:\Program Files\GRASS GIS 7.9\gui\wxpython\core\render.py` -> `C:\Program Files\GRASS GIS 7.9\gui\wxpython\core\render.py.bckp` 
-  `C:\Program Files\GRASS GIS 7.9\gui\wxpython\core\ws.py` -> `C:\Program Files\GRASS GIS 7.9\gui\wxpython\core\ws.py.bckp` 

2. Download these files:
- `https://raw.githubusercontent.com/OSGeo/grass/5db4a43d384ef6fc95983d74002ef80b863b9ac7/gui/wxpython/core/render.py`
- `https://raw.githubusercontent.com/OSGeo/grass/5db4a43d384ef6fc95983d74002ef80b863b9ac7/gui/wxpython/core/ws.py`

3. Overwrite these files with downloaded files:
-  `C:\Program Files\GRASS GIS 7.9\gui\wxpython\core\render.py` 
-  `C:\Program Files\GRASS GIS 7.9\gui\wxpython\core\ws.py` 

How to apply the #572 PR fix:

1. Make backup:
-  `C:\Program Files\GRASS GIS 7.9\gui\wxpython\vdigit\toolbars.py` -> `C:\Program Files\GRASS GIS 7.9\gui\wxpython\vdigit\toolbars.py.bckp` 

2. Download this file:
- `https://raw.githubusercontent.com/OSGeo/grass/0806c5fd7148e063f2e3815b58e97b1afc7815a9/gui/wxpython/vdigit/toolbars.py`

3. Overwrite this file with downloaded file:
-  `C:\Program Files\GRASS GIS 7.9\gui\wxpython\vdigit\toolbars.py`

**Closed** 2020-05-07 01:51 UTC
Labels: GUI, MacOS, bug
