### ISSUE TITLE
[Bug] Autogenerated GUI dialogs lack vertical scrollbars

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass#480] opened 2020-04-03 11:08 UTC
Some module windows have a content larger than can be displayed in a module window. Unfortunately almost all module windows lack vertical scrollbar and thus part of options are inaccessible. Only way around is to increase window size to ludicrous (for some windows it is 2 to 3 times the display size!).
Some of module windows (r.sun) do have a scrollbar, but it is waaaaay too short.

**To Reproduce**
Steps to reproduce the behaviour:

1. Launch r.sun or g.region or v.distance or i.maxlik
2. Dude, where are my options?!?

**Expected behaviour**
A scroll bar is displayed if whole window content doesn't fit into current window size.

**Screenshots**
r.sun window after scrolling to the bottom. No window resizing has been done. Full size of the r.sun window is approx. 1000x1300 px.
![attels](https://user-images.githubusercontent.com/17123023/78353938-a0777300-75b3-11ea-9e1d-12336736dcf3.png)

**System description (please complete the following information):**

- Operating System: Gentoo Linux
GRASS versija: 7.9.dev                                                          
Code revision: aa3ba0f16                                                        
Būvējuma datums: 2020-04-02                                                     
Būvēšanas platforma: x86_64-pc-linux-gnu                                        
GDAL: 3.0.4                                                                     
PROJ: 6.3.1                                                                     
GEOS: 3.8.1                                                                     
SQLite: 3.31.1                                                                  
Python: 3.6.10                                                                  
wxPython: 4.0.7.post2                                                           
Platforma: Linux-5.5.5-gentoo-x86_64

**Comment by petrasovaa** [comment] 2020-04-06 21:09
I can't reproduce on Ubuntu, yes the options are hidden, but there is a scrollbar and it works ok, you can scroll all the way down. Just in case, do you have some kind of special screen setup? Like 4k monitor with 200% scaling set?

**Comment by marisn** [comment] 2020-04-10 09:34
> Just in case, do you have some kind of special screen setup? Like 4k monitor with 200% scaling set?

Nothing fancy. I have a 1440x900 screen with ordinary Xorg + KDE (KWin). This issue is not a new one — it has been present already for some longer time (months). Recently I started to record educational videos about GRASS GIS and thus do not want to show it in a bad light...

Any hints where I could add some extra instrumentation (printfs) to shed more light into this issue?

Here's list of all wx related stuff I have on my 11 years old Gentoo install:
equery l '\*wx\*'
Searching for \*wx\* ...
[IP-] [  ] app-eselect/eselect-wxwidgets-20180529:0
[IP-] [  ] dev-python/wxpython-4.0.7:4.0
[IP-] [  ] x11-libs/wxGTK-3.0.4-r2:3.0
[IP-] [  ] x11-libs/wxGTK-3.0.4-r302:3.0-gtk3

**Comment by petrasovaa** [comment] 2020-04-17 13:28
Fixed by #503

**Closed by petrasovaa** 2020-04-17 13:28 UTC
Labels: GUI, bug

**Comment by marisn** [comment] 2020-04-18 07:03
> Fixed by #503

Thanks, now module dialogs work as expected :-)
