### ISSUE TITLE
[Bug] wxGUI: map display incomplete when restoring settings from project file (gxw)

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass#466] opened 2020-03-30 20:40 UTC
**Describe the bug**

Starting the wxGUI (here on a dual-screen system consisting of laptop and external monitor) leads to an incomplete initial map rendering:

`g.gui workspace=~/santana.gxw &`

leads to (full monitor view):

![grass_monitor1](https://user-images.githubusercontent.com/1295172/77959486-f065e980-72d6-11ea-99ed-8b729399a112.png)

Then, after double click on border it is properly refreshed:

![grass_monitor2_double_click](https://user-images.githubusercontent.com/1295172/77959495-f4920700-72d6-11ea-82eb-b451f64b4145.png)

**Expected behavior**

The map display properties need to be correctly computed like it apparently happens after reducing the map window size. Maybe just an internal refresh is missing?

**System description (please complete the following information):**

```
Linux Fedora 32

GRASS 7.8.3dev (latlong_wgs84):~ > g.version -rge
version=7.8.3dev
date=2020
revision=42388e55e
build_date=2020-03-15
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=
libgis_date=
WARNING: GRASS GIS libgis version and date number not available
proj=5.2.0
gdal=2.3.2
geos=3.7.1
sqlite=3.30.0
```

**Comment by petrasovaa** [comment] 2020-03-31 02:13
Duplicate of https://trac.osgeo.org/grass/ticket/2840, probably close the one on trac.

**Comment by neteler** [comment] 2020-03-31 09:05
> Duplicate of https://trac.osgeo.org/grass/ticket/2840, probably close the one on trac.

Cited from old trac ticket:
 _See this thread: ​http://lists.osgeo.org/pipermail/grass-user/2015-December/073499.html_ 

Bug report to be continued here, closing trac ticket.

**Closed** 2020-05-07 02:05 UTC
Labels: GUI, backport_needed, bug
