### ISSUE TITLE
[Bug] g.gui.iclass uses deprecated mlab function 

### ISSUE THREAD

**Issue by CarlosGrohmann** [OSGeo/grass#598] opened 2020-05-07 20:36 UTC
**Description**
I'm running 7.9 (from github) in Linux Manjaro. Matplotlib is installed and I use it elsewhere. Python 3.8.2.
When trying to run g.gui.iclass, I got the warning "unable needed to import packages for scatter plot". The error reported is that it can't import "dist_point_to_segment". From what I found, this function was deprecated in recent versions of matplotlib. See here: https://github.com/ESMG/pyroms/issues/18

**To Reproduce**
Click on wxgui menu "Imagery - Classify Image - interactive input for supervised classification" 

**Expected behavior**
I expected the tool to open without issues, as I have matplotlib working

**Screenshots**
![bug_gguiiclass](https://user-images.githubusercontent.com/1870265/81342224-44f44580-9089-11ea-869b-a61f5b0fc265.png)

**System description **
- Operating System: Linux Manjaro 
- GRASS GIS version 7.9.dev

version=7.9.dev
date=2020
revision=ad079931e
build_date=2020-05-04
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=f89b009b5
libgis_date=2020-04-24T11:32:32+00:00
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1

**Additional context**

**Comment by nilason** [comment] 2020-05-07 20:53
This is duplicate of https://github.com/OSGeo/grass/issues/461. May be closed as such.

**Closed** 2020-05-08 01:11 UTC
Labels: bug
