### ISSUE TITLE
[Bug] t.register and t.rast.extract fails if raster are not in same mapset

### ISSUE THREAD

**Issue by anikaweinmann** [OSGeo/grass#1791] opened 2021-08-13 13:43 UTC
**Describe the bug**
`t.register` and `t.rast.extract` only work if the raster maps are in the current mapset
**To Reproduce**
I used the modis_lst mapset to test it and create a new mapset in the same location
1. Create a new mapset in the same location as the modis_lst mapset ist: `grass78 -c grassdata/nc_spm_08_grass7/test`
2. Excute:
```
t.create output=test description=test title=test
t.register input=test maps=MOD11B3.A2016306.h11v05.single_LST_Day_6km@modis_lst,MOD11B3.A2016336.h11v05.single_LST_Day_6km@modis_lst start=2016-11-01 increment="1 months"
```
3. See error
```
Gathering map information...
WARNUNG: Map is already registered in temporal database. Unable to update
         raster map <MOD11B3.A2016306.h11v05.single_LST_Day_6km@modis_lst>.
         Overwrite flag is not set.
WARNUNG: Map is already registered in temporal database. Unable to update
         raster map <MOD11B3.A2016336.h11v05.single_LST_Day_6km@modis_lst>.
         Overwrite flag is not set.
 100%
Registering maps in the space time dataset...
ERROR: Only maps from the same mapset can be registered
```
 
**Expected behavior**
Since the mapset are also written in the tgis sqlite.db i would expect that i can also register rasters in another mapset in my strds.

**Screenshots**

**System description (please complete the following information):**

- Operating System: Linux Mint 20.1
- GRASS GIS version: 7.8.6dev
g.version -reg
version=7.8.6dev
date=2021
revision=42f015eb5
build_date=2021-08-06
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=ffa09badd
libgis_date=2021-06-18T12:57:31+00:00
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1

**Comment by veroandreo** [comment] 2021-08-13 14:01
Is modis_lst mapset in the list of accessible mapsets of test? I'd try that first, within test mapset: g.mapsets mapset=modis_lst

**Comment by anikaweinmann** [comment] 2021-08-13 14:32
Also if I add the modis_lst mapset I get the ERROR:
```
g.mapsets operation=add mapset=modis_lst
t.rast.extract input=LST_Day_monthly@modis_lst output=test where="start_time > '2016-01-01 12:30:00'"
ERROR: Only maps from the same mapset can be registered
```

**Comment by veroandreo** [comment] 2021-08-13 14:53
AFAIU, following GRASS principles, STDS and maps within them can only be read from a mapset different to the one they live; eg, I have used a map from modis_lst to set the computational region in a different mapset, that's fine. I can also see the list of stds and list of maps in them. But my stds are always where the maps are, i.e., in the same mapset. I believe this is by design like this. See: https://grasswiki.osgeo.org/wiki/Temporal_data_processing#Best_practice_multi_user_management

IIUC, what you try to do with the t.extract command would mean to write new metadata into maps that are not in the current mapset, which is by design not possible in GRASS. 

@huhabla would you please enlighten us here?

**Comment by ninsbl** [comment] 2021-08-13 21:22
Looking at https://github.com/OSGeo/grass/blob/master/python/grass/temporal/register.py it seems to be by design.

However, I agree with @anikaweinmann that it would be useful to be able to register maps across mapsets. Given that both mapset and timestamp are stored in the temporal database, it might be possible to relax the requirement to write the timestamp to the GRASS map (filesystem) and then allow maps from other mapsets be registered in STDS in other mapsets. I have no idea how big a change that would be (number of affected modules) though.

Possible issues may occur when maps are removed and also at least t.remove may have to account for not deleting maps from other mapsets...

**Comment by mmacata** [comment] 2021-08-18 09:56
> Also if I add the modis_lst mapset I get the ERROR:
> 
> ```
> g.mapsets operation=add mapset=modis_lst
> t.rast.extract input=LST_Day_monthly@modis_lst output=test where="start_time > '2016-01-01 12:30:00'"
> ERROR: Only maps from the same mapset can be registered
> ```

Just an observation: this command works when complemented with expression and basename:
```
GRASS > t.rast.extract input=LST_Day_monthly@modis_lst output=test where="start_time > '2016-01-01 12:30:00'"  \
    expression="1.0 * LST_Day_monthly@modis_lst" basename=test
WARNING: Overwriting space time raster dataset <test> and unregistering all
         maps
 100%
```

**Comment by veroandreo** [comment] 2021-08-19 18:17
Using no expression and adding basename, yields the same message as originally reported, i.e., maps are just the same as in the original strds, hence cannot be registered in a mapset different to where they live. Using expression and basename seems to work because it implies an r.mapcalc run and hence creation of new maps (even if multiplied by 1.0 and no real changes, and hence it copies the maps to the current mapset) in the current mapset so they can be registered.

**Comment by metzm** [comment] 2021-08-21 20:52
> However, I agree with @anikaweinmann that it would be useful to be able to register maps across mapsets. Given that both mapset and timestamp are stored in the temporal database, it might be possible to relax the requirement to write the timestamp to the GRASS map (filesystem) and then allow maps from other mapsets be registered in STDS in other mapsets. I have no idea how big a change that would be (number of affected modules) though.

At least `t.register` should IMHO not modify existing raster maps, but simply add them to the temporal database. This means that if time stamps provided with an input file to `t.register` do not match the timestamp files of raster maps to be registered, the timestamp files should not be modified by `t.register`. All other `t.*` modules (should) use time information from the TGIS db and don't query the rasters' timestamps files.

The same is true for band references.

**Comment by metzm** [comment] 2021-10-05 07:35
Addressed by https://github.com/OSGeo/grass/pull/1924

**Closed** 2022-03-14 17:26 UTC
Labels: bug
