### ISSUE TITLE
[Bug] Change color letters from Layer Manager

### ISSUE THREAD

**Issue by mauriciovancine** [OSGeo/grass#662] opened 2020-05-22 19:31 UTC
**Describe the bug**
The color of the layers is white and is a bit confusing to see.

**Screenshots**
![layer_maneger](https://user-images.githubusercontent.com/13386924/82703066-9a178600-9c49-11ea-87df-59d0554e3b3c.png)

**System description (please complete the following information):**
- Operating System: [Ubuntu 20.04]
- GRASS GIS version [7.8.3]

<!---

- details about further software components
version=7.8.3
date=2020
revision=exported
build_date=2020-05-05
build_platform=x86_64-pc-linux-gnu
build_off_t_size=8
libgis_revision=2020-05-05T23:27:51+00:00
libgis_date=2020-05-05T23:27:51+00:00
proj=6.3.1
gdal=3.0.4
geos=3.8.0
sqlite=3.31.1

**Comment by wenzeslaus** [comment] 2020-05-22 19:50
Thanks for reporting it here. Now when I see your theme, I can reproduce it with _HighContrastInverse_ theme. We have to analyze this more to decide if this is something we need to fix, or it is a duplicate of #591, or it is something to report upstream, i.e., to wxPython.

**Comment by mauriciovancine** [comment] 2020-05-22 19:57
No problem.

The problem is that the lyrics don't appear in clear themes either ...

Did I change anything else in "Tweaks" that affected this?

Anyway, I appreciate the availability.

**Comment by petrasovaa** [comment] 2020-05-22 20:13
> The problem is that the lyrics don't appear in clear themes either ...

Could you show a screenshot? It seems fine here.
> 
> Did I change anything else in "Tweaks" that affected this?
> 
Which theme specifically? Could you test default/standard themes?

I am leaning towards closing this and you could follow up in this wx issue I created:
https://github.com/wxWidgets/Phoenix/issues/1647

**Comment by mauriciovancine** [comment] 2020-05-23 15:24
Hi Anna.

> Could you show a screenshot? It seems fine here.
![layer_manager](https://user-images.githubusercontent.com/13386924/82734096-de109680-9cee-11ea-988c-d246b242b3d3.png)

> Which theme specifically? Could you test default/standard themes?
I'm using in the Tweaks:

Applications: Flat-Remix-GTK-Green-Dark
Shell: Matcha-dark-sea

I tested using the Yaru theme and the problem is solved.

The Flat-Remix-GTK-Green-Dark transform the letters in white and this is the problem.

> I am leaning towards closing this and you could follow up in this wx issue I created:
wxWidgets/Phoenix#1647
I agree.

Thanks for your help.

Kind regards.

**Comment by marisn** [comment] 2020-05-24 09:38
This is a subset of #591 Even when the issue in wxPython will be fixed, we'll be left with bunch of hardcoded colour values. Thus it depends on our preferences — to track each issue as a separate one or just as a part of one larger task.

**Closed** 2020-05-24 17:27 UTC
Labels: bug
